ALTER TABLE projects ADD COLUMN target_branch TEXT NOT NULL DEFAULT 'main';
ALTER TABLE projects ADD COLUMN auto_merge INTEGER NOT NULL DEFAULT 1;
ALTER TABLE projects ADD COLUMN sync_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN sync_remote TEXT;
