[package]
publish = false
name = "djinn-compaction"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
djinn-provider = { path = "../djinn-provider" }
anyhow = "1"
futures = "0.3"
serde_json = "1"
sha2 = "0.10"
tracing = "0.1"
workspace-hack.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["test-util", "macros", "rt-multi-thread"] }

[lints]
workspace = true
