#!/usr/bin/env perl
# Offline evaluator; JSON::PP is core on supported Perl installations.
use strict; use warnings; use JSON::PP; use Digest::SHA qw(sha256_hex); use Getopt::Long qw(GetOptions);
use File::Basename qw(dirname);
use File::Spec;
my $MIB=1024*1024; my $GIB=1024*$MIB; my $RAW='memory-sustainability-raw/v1'; my $RESULT='memory-sustainability-report/v1'; my @PHASES=qw(T0 graph_install T1 burst T2);
my ($input,$json_out,$report_out); GetOptions('input=s'=>\$input,'json-out=s'=>\$json_out,'report-out=s'=>\$report_out) or die "usage: evaluate.pl --input raw.json --json-out report.json --report-out report.md\n";
die "usage: evaluate.pl --input raw.json --json-out report.json --report-out report.md\n" unless $input && $json_out && $report_out;
my $JSON=JSON::PP->new->canonical(1)->pretty(1)->allow_nonref(0);
sub canon { $JSON->encode($_[0]) }
sub read_json { my($p)=@_; open my $fh,'<:raw',$p or die "$p: $!"; local $/; my $x=<$fh>; close $fh; decode_json($x) }
sub write_raw { my($p,$x)=@_; open my $fh,'>:raw',$p or die "$p: $!"; print $fh $x; close $fh }
sub is_hash { ref($_[0]) eq 'HASH' }
sub bytes { my($value,$path,$errors)=@_; if(!defined($value)||ref($value)||$value!~/\A\d+\z/){push @$errors,"$path must be a non-negative integer byte count";return undef} return 0+$value }
sub identity { my($x,$run,$image,$path,$errors)=@_; push @$errors,"$path.run_id does not match top-level run_id" if !defined($x->{run_id})||$x->{run_id} ne $run; push @$errors,"$path.image_id does not match candidate image_id" if !defined($x->{image_id})||$x->{image_id} ne $image }
sub check { my($name,$observed,$threshold,$units,$evidence,$ok,$errors)=@_; my $r={name=>$name,status=>@$errors?'error':$ok?'pass':'fail',observed=>$observed,threshold=>$threshold,units=>$units,evidence=>$evidence}; $r->{errors}=$errors if @$errors; return $r }
sub evaluate_run {
 my($raw)=@_; my @errors; return [check('input_contract',undef,'raw object','n/a',[],0,['raw must be an object'])] unless is_hash($raw);
 push @errors,"unsupported raw schema ".(defined($raw->{schema})?"'$raw->{schema}'":'undef')."; expected $RAW" if !defined($raw->{schema})||$raw->{schema} ne $RAW;
 my($run,$image)=($raw->{run_id},$raw->{candidate_image_id}); push @errors,'run_id must be a non-empty string' unless defined($run)&&!ref($run)&&length($run); push @errors,'candidate_image_id must be a non-empty string' unless defined($image)&&!ref($image)&&length($image);
 my $limit=bytes($raw->{cgroup_limit_bytes},'cgroup_limit_bytes',\@errors); push @errors,'cgroup_limit_bytes must be exactly 4294967296 (4 GiB)' if !defined($limit)||$limit!=4*$GIB;
 my $samples=$raw->{samples}; if(ref($samples) ne 'ARRAY'){push @errors,'samples must be an array';$samples=[]} my %by;
 for my $i(0..$#$samples){my $s=$samples->[$i];my $p="samples[$i]";if(!is_hash($s)){push @errors,"$p must be an object";next} identity($s,$run,$image,$p,\@errors);my $phase=$s->{phase};if(!defined($phase)||!grep {$phase eq $_}@PHASES){push @errors,"$p.phase must be one of ".join(', ',@PHASES);next}push @errors,"duplicate required phase $phase" if exists $by{$phase};$by{$phase}=[$i,$s];for my $k(qw(server_rss_bytes warm_job_rss_bytes jemalloc_retained_bytes oom_kill_count restart_count)){bytes($s->{$k},"$p.$k",\@errors)}push @errors,"$p.graph_generation_id must be a non-empty string" unless defined($s->{graph_generation_id})&&!ref($s->{graph_generation_id})&&length($s->{graph_generation_id})}
 for my $phase(@PHASES){push @errors,"missing required phase $phase" unless exists $by{$phase}}
 my $routes=$raw->{route_samples};if(ref($routes) ne 'ARRAY'||!@$routes){push @errors,'route_samples must be a non-empty array';$routes=[]}my @deltas;
 for my $i(0..$#$routes){my $s=$routes->[$i];my $p="route_samples[$i]";if(!is_hash($s)){push @errors,"$p must be an object";next}identity($s,$run,$image,$p,\@errors);push @errors,"$p.http_status must be 200 or 304" unless defined($s->{http_status})&&($s->{http_status}==200||$s->{http_status}==304);my($before,$after)=(bytes($s->{rss_before_bytes},"$p.rss_before_bytes",\@errors),bytes($s->{rss_after_bytes},"$p.rss_after_bytes",\@errors));push @deltas,$after-$before if defined($before)&&defined($after)}
 my $board=$raw->{board_passes};if(ref($board) ne 'ARRAY'||!@$board){push @errors,'board_passes must be a non-empty array';$board=[]}my @times;
 for my $i(0..$#$board){my $s=$board->[$i];my $p="board_passes[$i]";if(!is_hash($s)){push @errors,"$p must be an object";next}identity($s,$run,$image,$p,\@errors);my $d=bytes($s->{duration_ms},"$p.duration_ms",\@errors);push @times,$d if defined$d}
 my $valid=!@errors; my $val=sub{my($phase,$key)=@_;return exists($by{$phase})?$by{$phase}[1]{$key}:undef}; my @sample_values=map {$by{$_}[1]} grep {exists $by{$_}}@PHASES;
 my($server_peak,$warm_peak)=(undef,undef);$server_peak=(sort{$b<=>$a}map{$_->{server_rss_bytes}}@sample_values)[0] if @sample_values;$warm_peak=(sort{$b<=>$a}map{$_->{warm_job_rss_bytes}}@sample_values)[0] if @sample_values;my $route_peak=@deltas?(sort{$b<=>$a}@deltas)[0]:undef;my $board_peak=@times?(sort{$b<=>$a}@times)[0]:undef;
 my($t1,$t2)=($val->('T1','server_rss_bytes'),$val->('T2','server_rss_bytes'));my($r1,$r2)=($val->('T1','jemalloc_retained_bytes'),$val->('T2','jemalloc_retained_bytes'));my $rss_limit=defined($t1)?(($t1*10/100)>128*$MIB?int($t1*10/100):128*$MIB):undef;my $rss_delta=defined($t1)&&defined($t2)?$t2-$t1:undef;my $retained=defined($r1)&&defined($r2)?$r2-$r1:undef;
 my(@oom,@restart,@gen);for my $p(@PHASES){push @oom,$val->($p,'oom_kill_count');push @restart,$val->($p,'restart_count');push @gen,$val->($p,'graph_generation_id')}my @counter_errors; if($valid){for my $pair([\@oom,'oom_kill_count'],[\@restart,'restart_count']){my($v,$n)=@$pair;for my $i(1..$#$v){push @counter_errors,"$n is not monotonic" if $v->[$i]<$v->[$i-1]}}}
 my @present=grep {exists $by{$_}} @PHASES; my $ev={server_peak=>[map{"/samples/$by{$_}[0]/server_rss_bytes"}@present],warm_peak=>[map{"/samples/$by{$_}[0]/warm_job_rss_bytes"}@present],routes=>[map{"/route_samples/$_"}0..$#$routes],board=>[map{"/board_passes/$_/duration_ms"}0..$#$board],phases=>[map{"/samples/$by{$_}[0]"}@present]};
 return [check('server_peak',$server_peak,3584*$MIB,'bytes',$ev->{server_peak},$valid&&defined($server_peak)&&$server_peak<=3584*$MIB,\@errors),check('warm_job_peak',$warm_peak,3584*$MIB,'bytes',$ev->{warm_peak},$valid&&defined($warm_peak)&&$warm_peak<=3584*$MIB,\@errors),check('route_rss_delta',$route_peak,32*$MIB,'bytes',$ev->{routes},$valid&&defined($route_peak)&&$route_peak<=32*$MIB,\@errors),check('board_pass_duration',$board_peak,120000,'milliseconds',$ev->{board},$valid&&defined($board_peak)&&$board_peak<=120000,\@errors),check('oom_delta',$valid?$oom[-1]-$oom[0]:undef,0,'events',$ev->{phases},$valid&&!@counter_errors&&$oom[-1]==$oom[0],[ @errors,@counter_errors ]),check('restart_delta',$valid?$restart[-1]-$restart[0]:undef,0,'events',$ev->{phases},$valid&&!@counter_errors&&$restart[-1]==$restart[0],[ @errors,@counter_errors ]),check('same_graph_generation',\@gen,'one unchanged generation','identity',$ev->{phases},$valid&&scalar(keys %{ {map {$_=>1}@gen} })==1,\@errors),check('t2_rss_delta',$rss_delta,$rss_limit,'bytes',['/samples/T1/server_rss_bytes','/samples/T2/server_rss_bytes'],$valid&&defined($rss_delta)&&defined($rss_limit)&&$rss_delta<=$rss_limit,\@errors),check('t2_jemalloc_retained_delta',$retained,256*$MIB,'bytes',['/samples/T1/jemalloc_retained_bytes','/samples/T2/jemalloc_retained_bytes'],$valid&&defined($retained)&&$retained<=256*$MIB,\@errors)];
}
sub render {my($report)=@_;my @r=('# Memory-sustainability evaluation','',"Candidate release status: **".uc($report->{candidate}{status}).'**','', '| Check | Status | Observed | Threshold | Units | Evidence |','|---|---|---:|---:|---|---|');for my $c(@{$report->{candidate}{checks}}){push @r,"| $c->{name} | $c->{status} | ".(defined$c->{observed}?ref($c->{observed})?canon($c->{observed}):$c->{observed}:'null')." | ".(defined$c->{threshold}?$c->{threshold}:'null')." | $c->{units} | ".join(', ',@{$c->{evidence}}).' |'}if($report->{pre_change_diagnostic}){push @r,'','## Pre-change-image diagnostic (non-release-gating)','',"Diagnostic status: **".uc($report->{pre_change_diagnostic}{status}).'**. This section cannot change the candidate release status.'}return join("\n",@r)."\n"}
my $document;eval{$document=read_json($input)}; $document={candidate=>{schema=>'invalid',error=>$@}} if $@;my $checks=evaluate_run($document->{candidate});my $pass=!grep {$_->{status} ne 'pass'}@$checks;my $report={schema=>$RESULT,candidate=>{status=>$pass?'pass':'fail',checks=>$checks,raw_measurements=>$document->{candidate}},raw_input_sha256=>sha256_hex(canon($document))};if(exists $document->{pre_change_diagnostic}){my $d=evaluate_run($document->{pre_change_diagnostic});$report->{pre_change_diagnostic}={label=>'pre-change-image diagnostic; not release gating',status=>!grep($_->{status} ne 'pass',@$d)?'pass':'fail',checks=>$d,raw_measurements=>$document->{pre_change_diagnostic}}}$report->{human_report}=render($report);write_raw($json_out,canon($report));write_raw($report_out,$report->{human_report});exit($pass?0:1);
