/**
 * Generate TypeScript types from the Rust-emitted JSON Schema for
 * `/api/admin/usage`.
 *
 * Source of truth: `server/schemas/usage-analytics.schema.json`
 *   — produced by `cargo test -p djinn-server export_schemas_to_file`
 *     or the `export-usage-schema` binary.
 *
 * Output: `ui/src/api/generated/usage-analytics.gen.ts`
 *
 * Usage:
 *   pnpm usage:types          # regenerate from schema
 *   pnpm usage:types:check    # regenerate + assert no drift
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const uiRoot = path.resolve(__dirname, "..");

const SCHEMA_PATH = path.resolve(
  uiRoot,
  "../server/schemas/usage-analytics.schema.json",
);
const OUT_PATH = path.resolve(
  uiRoot,
  "src/api/generated/usage-analytics.gen.ts",
);

type JsonSchema = Record<string, unknown>;

/**
 * Strip `$schema` draft URIs, `additionalProperties` (schemars defaults to
 * `true` which produces unwanted `[k: string]: any` index signatures), and
 * convert schemars v1 `"type": ["string", "null"]` to `"type": "string"`
 * with a sibling `"nullable": true`.
 */
function normalizeSchema(raw: JsonSchema): JsonSchema {
  const replacer = (value: unknown): unknown => {
    if (Array.isArray(value)) {
      return value.map(replacer);
    }
    if (value && typeof value === "object") {
      const record = value as Record<string, unknown>;
      const next: Record<string, unknown> = {};

      for (const [key, current] of Object.entries(record)) {
        // Strip JSON-Schema meta-keywords that confuse the compiler.
        if (key === "$schema") continue;

        // Replace additionalProperties with false to avoid `[k: string]: any`
        // index signatures.  schemars v1 emits `additionalProperties: true`
        // by default for all structs.
        if (key === "additionalProperties") {
          next["additionalProperties"] = false;
          continue;
        }

        // schemars v1 emits `type: ["string", "null"]` for Option<T>.
        // Convert to `type: "string"` so the compiler emits `T | null`.
        if (
          key === "type" &&
          Array.isArray(current) &&
          current.length === 2 &&
          current.includes("null")
        ) {
          const nonNull = current.find((t: string) => t !== "null");
          next["type"] = nonNull;
          next["nullable"] = true;
          continue;
        }

        next[key] = replacer(current);
      }

      return next;
    }
    return value;
  };

  return replacer(raw) as JsonSchema;
}

async function compileType(
  name: string,
  schema: JsonSchema,
): Promise<string> {
  return compile(schema, name, {
    bannerComment: "",
    format: false,
    unknownAny: false,
    strictIndexSignatures: false,
    additionalProperties: false,
  });
}

async function main(): Promise<void> {
  const raw = await readFile(SCHEMA_PATH, "utf8");
  const parsed = JSON.parse(raw) as JsonSchema;

  const definitions = parsed["definitions"] as Record<string, JsonSchema>;
  if (!definitions) {
    throw new Error("Schema missing 'definitions' key");
  }

  const sections: string[] = [];

  // ── Query / filter type ────────────────────────────────────────────────
  const querySchema = normalizeSchema(definitions["UsageQuery"]);
  const queryType = await compileType("UsageQuery", querySchema);
  sections.push(
    "// ── Query / filter parameters ─────────────────────────────────────────────",
    queryType,
  );

  // ── Response type (includes $defs for sub-DTOs) ───────────────────────
  const responseSchema = normalizeSchema(definitions["UsageResponse"]);
  const responseType = await compileType("UsageResponse", responseSchema);
  sections.push(
    "// ── Response ─────────────────────────────────────────────────────────────",
    responseType,
  );

  // ── Assemble ──────────────────────────────────────────────────────────
  const content = [
    "/* eslint-disable */",
    "// Auto-generated by ui/scripts/generate-usage-types.ts — DO NOT EDIT.",
    "// Source of truth: server/schemas/usage-analytics.schema.json",
    "// Regenerate with: pnpm usage:types",
    "",
    ...sections,
    "",
  ].join("\n");

  await mkdir(path.dirname(OUT_PATH), { recursive: true });
  await writeFile(OUT_PATH, content, "utf8");

  process.stderr.write(
    `Wrote ${OUT_PATH.replace(uiRoot + "/", "")} (${content.length} bytes)\n`,
  );
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`Failed to generate usage analytics types: ${message}\n`);
  process.exitCode = 1;
});
