//! Slot-boundary admission; provider I/O remains outside this coordinator.
use djinn_db::{ModelTurnAcquireInput,ModelTurnAcquireOutcome,ModelTurnAdmissionPhase,ModelTurnAdmissionRepository,ModelTurnAdmissionWait,ModelTurnDecisionKind,ModelTurnDecisionRecordInput,ModelTurnLeaseIdentity,ModelTurnLeaseMutationOutcome,ModelTurnLeaseReconciliationInput,ModelTurnLeaseTerminalOutcome};
use djinn_provider::{ProviderAttemptPlanV1,ProviderAttemptTerminalV1,ProviderOutcomeV1}; use sha2::{Digest,Sha256};
#[derive(Clone,Debug)] pub struct ModelTurnAdmissionRequest { pub credential_id:String,pub request_id:String,pub owner_pod_uid:Option<String>,pub generation:i64 }
#[derive(Clone,Debug)] pub struct ModelTurnSendPermit { pub lease:Option<ModelTurnLeaseIdentity> }
#[derive(Clone,Debug)] pub enum ModelTurnPreparation { Permit(ModelTurnSendPermit),Wait(ModelTurnAdmissionWait),Rejected }
#[derive(Clone)] pub struct ModelTurnAdmissionCoordinator { repository:ModelTurnAdmissionRepository }
impl ModelTurnAdmissionCoordinator { pub fn new(repository:ModelTurnAdmissionRepository)->Self { Self{repository} }
pub async fn prepare(&self,plan:&ProviderAttemptPlanV1,request:ModelTurnAdmissionRequest)->djinn_db::Result<ModelTurnPreparation>{ let Some(pool)=self.repository.resolve_pool(&request.credential_id,&plan.scope.provider_id,&plan.scope.model_id).await? else{return Ok(ModelTurnPreparation::Rejected)}; let fp=format!("sha256:{:x}",Sha256::digest(request.request_id.as_bytes())); match pool.phase { ModelTurnAdmissionPhase::Shadow=>{self.repository.record_decision(ModelTurnDecisionRecordInput{pool_id:pool.id,request_fingerprint:fp,generation:request.generation,decision:ModelTurnDecisionKind::ShadowPermit,diagnostic:None}).await?;Ok(ModelTurnPreparation::Permit(ModelTurnSendPermit{lease:None}))}, ModelTurnAdmissionPhase::Enforce=>match self.repository.acquire_turn(ModelTurnAcquireInput{pool_id:pool.id,request_id:request.request_id,owner_pod_uid:request.owner_pod_uid,generation:request.generation,debits:plan.debits.clone()}).await? { ModelTurnAcquireOutcome::Admitted{lease,..}=>{let identity=lease.identity;match self.repository.mark_dispatching(&identity).await? { ModelTurnLeaseMutationOutcome::Applied|ModelTurnLeaseMutationOutcome::Idempotent=>Ok(ModelTurnPreparation::Permit(ModelTurnSendPermit{lease:Some(identity)})),ModelTurnLeaseMutationOutcome::Fenced=>Ok(ModelTurnPreparation::Rejected)}},ModelTurnAcquireOutcome::Wait(wait)=>Ok(ModelTurnPreparation::Wait(wait)),ModelTurnAcquireOutcome::Rejected(_)=>Ok(ModelTurnPreparation::Rejected)},_=>Ok(ModelTurnPreparation::Rejected)}}
pub async fn mark_active(&self,identity:&ModelTurnLeaseIdentity)->djinn_db::Result<ModelTurnLeaseMutationOutcome>{self.repository.mark_active(identity).await}
pub async fn reconcile(&self,identity:ModelTurnLeaseIdentity,outcome:&ProviderOutcomeV1)->djinn_db::Result<ModelTurnLeaseMutationOutcome>{let terminal=match outcome.terminal {ProviderAttemptTerminalV1::Completed=>ModelTurnLeaseTerminalOutcome::Completed,ProviderAttemptTerminalV1::Aborted=>ModelTurnLeaseTerminalOutcome::Cancelled,ProviderAttemptTerminalV1::Failed(_)=>ModelTurnLeaseTerminalOutcome::Failed};self.repository.reconcile_lease(ModelTurnLeaseReconciliationInput{identity,outcome:terminal,authoritative_usage:outcome.authoritative_usage.clone(),detail:None}).await}}
