use strict; use warnings; use Test::More; use JSON::PP; use File::Temp qw(tempdir); use File::Spec;
my $root=File::Spec->catdir(File::Spec->curdir(),'server','docs','operational','memory-sustainability','evaluator'); my $script=File::Spec->catfile($root,'evaluate.pl'); my $M=1024*1024;
sub raw { my($r,$i)=('run-1','candidate@sha256:1'); my $s=sub {my($p,$rss,$warm,$ret)=@_;{run_id=>$r,image_id=>$i,phase=>$p,server_rss_bytes=>$rss//1024*$M,warm_job_rss_bytes=>$warm//1024*$M,jemalloc_retained_bytes=>$ret//512*$M,graph_generation_id=>'g-1',oom_kill_count=>0,restart_count=>0}}; return {schema=>'memory-sustainability-raw/v1',run_id=>$r,candidate_image_id=>$i,cgroup_limit_bytes=>4*1024*$M,samples=>[$s->('T0'),$s->('graph_install',3584*$M,3584*$M),$s->('T1'),$s->('burst'),$s->('T2',1152*$M,undef,768*$M)],route_samples=>[{run_id=>$r,image_id=>$i,http_status=>200,rss_before_bytes=>100*$M,rss_after_bytes=>132*$M}],board_passes=>[{run_id=>$r,image_id=>$i,duration_ms=>120000}]}}
sub run {my($candidate,$diag)=@_;my $d=tempdir(CLEANUP=>1);my $in="$d/in.json";my $out="$d/out.json";open my $f,'>',$in;print $f JSON::PP->new->canonical->encode({candidate=>$candidate,defined($diag)?(pre_change_diagnostic=>$diag):()});close$f;my $rc=system('perl',$script,'--input',$in,'--json-out',$out,'--report-out',"$d/out.md");open $f,'<',$out;local$/;my $x=decode_json(<$f>);close$f;return($x,$rc)}
my($good)=run(raw());is($good->{candidate}{status},'pass','exact numeric boundaries pass');like($good->{human_report},qr/server_peak \| pass/,'render generated from result');is_deeply($good->{candidate}{raw_measurements},raw(),'raw retained');
for my $case ([server_peak=>sub{$_[0]{samples}[1]{server_rss_bytes}++}],[warm_job_peak=>sub{$_[0]{samples}[1]{warm_job_rss_bytes}++}],[route_rss_delta=>sub{$_[0]{route_samples}[0]{rss_after_bytes}++}],[board_pass_duration=>sub{$_[0]{board_passes}[0]{duration_ms}++}],[t2_jemalloc_retained_delta=>sub{$_[0]{samples}[4]{jemalloc_retained_bytes}++}]) {my$x=raw();$case->[1]->($x);my($r)=run($x);my($c)=grep{$_->{name}eq$case->[0]}@{$r->{candidate}{checks}};is($c->{status},'fail',"$case->[0] just over fails")}
my$x=raw();$x->{samples}[4]{server_rss_bytes}++;my($r)=run($x);my($c)=grep{$_->{name}eq't2_rss_delta'}@{$r->{candidate}{checks}};is($c->{status},'fail','128 MiB branch just over fails');$x=raw();$x->{samples}[2]{server_rss_bytes}=2048*$M;$x->{samples}[4]{server_rss_bytes}=2048*$M+int(2048*$M/10);($r)=run($x);($c)=grep{$_->{name}eq't2_rss_delta'}@{$r->{candidate}{checks}};is($c->{status},'pass','10 percent branch passes');$x->{samples}[4]{server_rss_bytes}++;($r)=run($x);($c)=grep{$_->{name}eq't2_rss_delta'}@{$r->{candidate}{checks}};is($c->{status},'fail','10 percent just over fails');
for my $change(sub{$_[0]{samples}[0]{run_id}='mixed'},sub{$_[0]{samples}[4]{graph_generation_id}='drift'},sub{pop @{$_[0]{samples}}},sub{$_[0]{route_samples}[0]{rss_after_bytes}='32 MiB'},sub{$_[0]{samples}[4]{oom_kill_count}=1},sub{$_[0]{samples}[4]{restart_count}=1}){$x=raw();$change->($x);($r)=run($x);is($r->{candidate}{status},'fail','identity/safety/malformed evidence cannot pass')}
my$bad=raw();$bad->{samples}[1]{server_rss_bytes}++;($r)=run($bad,raw());is($r->{candidate}{status},'fail','candidate failure remains failure');is($r->{pre_change_diagnostic}{status},'pass','diagnostic reported separately');like($r->{human_report},qr/non-release-gating/,'diagnostic is labeled');done_testing();
