/**
 * citationResolver — turn a parsed citation into a concrete graph
 * node id (or a candidate list when the symbol form is ambiguous).
 *
 * File citations resolve client-side because the snapshot bridge formats
 * file keys as a stable `file:<path>`. Symbol citations require a
 * server round-trip to `code_graph search mode=name` to disambiguate
 * short names against the canonical graph.
 *
 * The 0.85 confidence cutoff is set in the plan
 * (§"Citation format & resolution flow"). Above the cutoff with a
 * single result, we pin directly. Otherwise the caller is expected to
 * render a candidate-list popover and let the user pick.
 */

import { searchSymbols, parseSearchHits, type SearchHit } from "@/api/codeGraph";
import {
  fileCitationToNodeId,
  type FileCitation,
  type ParsedCitation,
  type SymbolCitation,
} from "./citationParser";

/** Minimum top score (range 0..1) for an unambiguous symbol resolution. */
export const HIGH_CONFIDENCE_CUTOFF = 0.85;

export interface DirectResolution {
  status: "direct";
  citation: ParsedCitation;
  nodeId: string;
  /** Optional snippet pin for file citations with a line range. */
  startLine?: number | null;
  endLine?: number | null;
}

export interface AmbiguousResolution {
  status: "ambiguous";
  citation: SymbolCitation;
  hits: SearchHit[];
}

export interface MissingResolution {
  status: "missing";
  citation: SymbolCitation;
}

export type CitationResolution =
  | DirectResolution
  | AmbiguousResolution
  | MissingResolution;

/**
 * Inject point for tests / non-default backends. The default uses
 * the autogenerated MCP client; tests stub this out so the unit
 * tests don't need an HTTP fixture.
 */
export interface CodeGraphSearchClient {
  search(
    project: string,
    citation: SymbolCitation,
  ): Promise<SearchHit[]>;
}

const defaultSearchClient: CodeGraphSearchClient = {
  async search(project, citation) {
    const raw = await searchSymbols(project, citation.name, {
      limit: 8,
      kind_hint: citation.symbolKind,
    });
    return parseSearchHits(raw);
  },
};

/**
 * Resolve a parsed citation to a node id (or a candidate set).
 *
 * Per plan §612-619:
 *   - file form → direct, no network call.
 *   - symbol form, single hit ≥ 0.85 → direct.
 *   - symbol form, anything else → ambiguous (caller renders popover).
 */
export async function resolveCitation(
  citation: ParsedCitation,
  project: string,
  client: CodeGraphSearchClient = defaultSearchClient,
): Promise<CitationResolution> {
  if (citation.kind === "file") {
    return resolveFile(citation);
  }
  return resolveSymbol(citation, project, client);
}

export function resolveFile(citation: FileCitation): DirectResolution {
  return {
    status: "direct",
    citation,
    nodeId: fileCitationToNodeId(citation),
    startLine: citation.startLine,
    endLine: citation.endLine,
  };
}

async function resolveSymbol(
  citation: SymbolCitation,
  project: string,
  client: CodeGraphSearchClient,
): Promise<CitationResolution> {
  const hits = await client.search(project, citation);
  if (hits.length === 0) {
    return { status: "missing", citation };
  }

  // Sort by score desc so callers can rely on `hits[0]` being top.
  // The MCP server already returns hits this way for `mode=name`,
  // but defensive sort guards against future refactors.
  const sorted = [...hits].sort((a, b) => b.score - a.score);
  const top = sorted[0];

  if (sorted.length === 1 && top.score >= HIGH_CONFIDENCE_CUTOFF) {
    return {
      status: "direct",
      citation,
      nodeId: top.key,
    };
  }

  return { status: "ambiguous", citation, hits: sorted };
}
