[package]
publish = false
name = "djinn-lsp"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
djinn-core = { path = "../djinn-core" }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
dirs = "6"
libc = "0.2"
workspace-hack.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["test-util", "macros", "rt-multi-thread"] }
tempfile = "3"

[lints]
workspace = true
