[package]
publish = false
name = "djinn-log-rotator"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
axum = "0.8"
flate2 = "1"
libc = "0.2"
serde_json = "1"
thiserror = "2"
time = { version = "0.3", features = ["formatting", "macros", "parsing"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "signal"] }
uuid = { version = "1", features = ["v4"] }
workspace-hack.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile = "3"
tower = { version = "0.5", features = ["util"] }
