//! Generate a Dockerfile from an [`EnvironmentConfig`].
//!
//! Pure function. The output is a tuple of (Dockerfile string, script
//! bundle) — the builder Pod drops the Dockerfile + bundle into a
//! ConfigMap and runs `buildctl build` against it.
//!
//! Structure of the emitted Dockerfile:
//!
//! ```text
//! FROM <base>
//! COPY scripts/ /tmp/djinn-scripts/
//! RUN /tmp/djinn-scripts/base-<distro>.sh
//! RUN APT_PACKAGES="..." /tmp/djinn-scripts/install-system.sh
//! COPY --from=djinn/agent-worker:<sha> /opt/djinn/bin/djinn-agent-worker /opt/djinn/bin/djinn-agent-worker
//! RUN /tmp/djinn-scripts/install-agent-worker.sh
//! RUN TOOLCHAINS="stable 1.85.0" COMPONENTS="rust-analyzer" /tmp/djinn-scripts/install-rust.sh
//! RUN NODE_VERSIONS="20 22" PACKAGE_MANAGERS="pnpm" /tmp/djinn-scripts/install-node.sh
//! ENV RUST_LOG=info
//! RUN <post_build hook>
//! RUN rm -rf /tmp/djinn-scripts
//! ```
//!
//! Language blocks are emitted only when the corresponding
//! `config.languages.*` is `Some`. Workspace-level toolchain overrides
//! are aggregated into the space-separated env vars each installer
//! consumes (e.g. `TOOLCHAINS="stable 1.85.0"`), so one `RUN` line per
//! language covers every pinned version.

use std::collections::BTreeSet;
use std::fmt::Write;

use djinn_stack::environment::{
    Distro, EnvironmentConfig, HookCommand, Languages, NodeLanguage, RustLanguage,
};
use thiserror::Error;

use crate::scripts::SCRIPTS;

/// The agent-worker helper-image ref baked into the `COPY --from=...`
/// line. The tag is the sha of the worker binary used at build time.
/// Plumbed in from the caller so the Dockerfile string becomes
/// deterministic for a given input; `compute_environment_hash` mixes
/// it in, so a worker rebuild invalidates cached project images.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AgentWorkerImage {
    /// e.g. `djinn/agent-worker` — no tag, no sha.
    pub repository: String,
    /// e.g. `sha256-abc123…` or a semver tag; must be non-empty.
    pub reference: String,
}

impl AgentWorkerImage {
    pub fn new(repository: impl Into<String>, reference: impl Into<String>) -> Self {
        Self {
            repository: repository.into(),
            reference: reference.into(),
        }
    }

    fn full_ref(&self) -> String {
        format!("{}:{}", self.repository, self.reference)
    }
}

/// The output of [`generate_dockerfile`] — the Dockerfile string plus
/// the script bundle that needs to land alongside it in the builder
/// context.
#[derive(Debug, Clone)]
pub struct BuildContext {
    pub dockerfile: String,
    /// Each entry is `(relative_path_in_context, body)`. The generator
    /// always returns the full [`crate::scripts::SCRIPTS`] bundle so
    /// that every installer a project *might* reference is available —
    /// the alternative (per-config filtering) would leak into the hash
    /// as the config evolves.
    pub scripts: Vec<(String, String)>,
}

#[derive(Debug, Error)]
pub enum DockerfileError {
    #[error(
        "config.source = user-edited but schema_version = 0; refuse to build from an un-seeded row"
    )]
    UnseededConfig,
    #[error("config validation failed: {0}")]
    InvalidConfig(#[from] djinn_stack::environment::EnvironmentConfigError),
    #[error("agent-worker reference is empty — caller must plumb a real tag or sha")]
    MissingAgentWorkerRef,
    #[error("unknown language slug in workspace: {0}")]
    UnknownWorkspaceLanguage(String),
}

/// Generate the Dockerfile + script bundle for `config`.
///
/// `agent_worker` is the helper image the `djinn-agent-worker` binary
/// is copied from. The worker reference contributes to
/// [`crate::compute_environment_hash`], so replacing it (e.g. after a
/// worker rebuild) invalidates cached images.
pub fn generate_dockerfile(
    config: &EnvironmentConfig,
    agent_worker: &AgentWorkerImage,
) -> Result<BuildContext, DockerfileError> {
    if agent_worker.reference.trim().is_empty() {
        return Err(DockerfileError::MissingAgentWorkerRef);
    }
    config.validate()?;

    let mut df = String::new();
    writeln!(df, "# syntax=docker/dockerfile:1.7").unwrap();
    writeln!(df, "# Generated by djinn-image-builder — DO NOT EDIT.").unwrap();
    writeln!(df).unwrap();

    emit_from(&mut df, config);
    emit_copy_scripts(&mut df);
    emit_base(&mut df, config);
    emit_system_packages(&mut df, config);
    emit_agent_worker(&mut df, agent_worker);
    emit_language_blocks(&mut df, config)?;
    emit_env(&mut df, config);
    emit_post_build_hooks(&mut df, config);
    emit_cleanup(&mut df);

    Ok(BuildContext {
        dockerfile: df,
        scripts: SCRIPTS
            .iter()
            .map(|s| (format!("scripts/{}", s.name), s.body.to_string()))
            .collect(),
    })
}

// ---- section emitters ---------------------------------------------------

fn emit_from(df: &mut String, config: &EnvironmentConfig) {
    let image = match config.base.distro {
        Distro::Debian => format!("debian:{}", config.base.variant),
        Distro::Alpine => format!("alpine:{}", config.base.variant),
    };
    writeln!(df, "FROM {image}").unwrap();
}

fn emit_copy_scripts(df: &mut String) {
    writeln!(df, "COPY scripts/ /tmp/djinn-scripts/").unwrap();
    writeln!(df, "RUN chmod -R 0755 /tmp/djinn-scripts").unwrap();
}

fn emit_base(df: &mut String, config: &EnvironmentConfig) {
    let base = match config.base.distro {
        Distro::Debian => "base-debian.sh",
        Distro::Alpine => "base-alpine.sh",
    };
    writeln!(df, "RUN /tmp/djinn-scripts/{base}").unwrap();
}

fn emit_system_packages(df: &mut String, config: &EnvironmentConfig) {
    let apt = space_join_sorted(&config.system_packages.apt);
    let apk = space_join_sorted(&config.system_packages.apk);
    match (apt.is_empty(), apk.is_empty()) {
        (true, true) => {}
        (false, true) => writeln!(
            df,
            "RUN APT_PACKAGES=\"{apt}\" /tmp/djinn-scripts/install-system.sh"
        )
        .unwrap(),
        (true, false) => writeln!(
            df,
            "RUN APK_PACKAGES=\"{apk}\" /tmp/djinn-scripts/install-system.sh"
        )
        .unwrap(),
        (false, false) => writeln!(
            df,
            "RUN APT_PACKAGES=\"{apt}\" APK_PACKAGES=\"{apk}\" /tmp/djinn-scripts/install-system.sh"
        )
        .unwrap(),
    }
}

fn emit_agent_worker(df: &mut String, agent_worker: &AgentWorkerImage) {
    writeln!(
        df,
        "COPY --from={} /opt/djinn/bin/djinn-agent-worker /opt/djinn/bin/djinn-agent-worker",
        agent_worker.full_ref()
    )
    .unwrap();
    writeln!(df, "RUN /tmp/djinn-scripts/install-agent-worker.sh").unwrap();
}

fn emit_language_blocks(
    df: &mut String,
    config: &EnvironmentConfig,
) -> Result<(), DockerfileError> {
    emit_rust_block(df, &config.languages, config);
    emit_node_block(df, &config.languages, config);
    emit_python_block(df, &config.languages, config);
    emit_go_block(df, &config.languages, config);
    emit_java_block(df, &config.languages, config);
    emit_ruby_block(df, &config.languages, config);
    emit_dotnet_block(df, &config.languages);
    emit_clang_block(df, &config.languages);

    // Catch misspellings — if a workspace declares a language no
    // installer covers, fail the build rather than silently dropping it.
    let known = ["rust", "node", "python", "go", "java", "ruby", "dotnet", "clang"];
    for ws in &config.workspaces {
        if !known.contains(&ws.language.as_str()) {
            return Err(DockerfileError::UnknownWorkspaceLanguage(ws.language.clone()));
        }
    }
    Ok(())
}

fn emit_rust_block(df: &mut String, languages: &Languages, config: &EnvironmentConfig) {
    let Some(rust) = &languages.rust else { return };
    let toolchains = aggregate_rust_toolchains(rust, config);
    let components = space_join_sorted(&rust.components);
    let targets = space_join_sorted(&rust.targets);
    let mut line = format!(
        "RUN TOOLCHAINS=\"{}\" DEFAULT_TOOLCHAIN=\"{}\"",
        space_join(toolchains.iter().copied()),
        rust.default_toolchain
    );
    if !components.is_empty() {
        line.push_str(&format!(" COMPONENTS=\"{components}\""));
    }
    if !targets.is_empty() {
        line.push_str(&format!(" TARGETS=\"{targets}\""));
    }
    line.push_str(" /tmp/djinn-scripts/install-rust.sh");
    writeln!(df, "{line}").unwrap();
}

/// Workspace overrides come from either `workspace.toolchain` (rust)
/// or `workspace.version` (node/python/go). For Rust specifically we
/// use `toolchain` and de-dup against the language default.
fn aggregate_rust_toolchains<'a>(
    rust: &'a RustLanguage,
    config: &'a EnvironmentConfig,
) -> Vec<&'a str> {
    let mut seen: BTreeSet<&str> = BTreeSet::new();
    let mut out: Vec<&str> = Vec::new();
    for tc in std::iter::once(rust.default_toolchain.as_str()).chain(
        config
            .workspaces
            .iter()
            .filter(|ws| ws.language == "rust")
            .filter_map(|ws| ws.toolchain.as_deref()),
    ) {
        if seen.insert(tc) {
            out.push(tc);
        }
    }
    out
}

fn emit_node_block(df: &mut String, languages: &Languages, config: &EnvironmentConfig) {
    let Some(node) = &languages.node else { return };
    let versions = aggregate_node_versions(node, config);
    let mut line = format!(
        "RUN NODE_VERSIONS=\"{}\" DEFAULT_NODE=\"{}\"",
        space_join(versions.iter().copied()),
        node.default_version
    );
    let package_managers = aggregate_node_pms(node, config);
    if !package_managers.is_empty() {
        line.push_str(&format!(
            " PACKAGE_MANAGERS=\"{}\"",
            space_join(package_managers.iter().copied())
        ));
    }
    line.push_str(" /tmp/djinn-scripts/install-node.sh");
    writeln!(df, "{line}").unwrap();
}

fn aggregate_node_versions<'a>(
    node: &'a NodeLanguage,
    config: &'a EnvironmentConfig,
) -> Vec<&'a str> {
    let mut seen: BTreeSet<&str> = BTreeSet::new();
    let mut out: Vec<&str> = Vec::new();
    for v in std::iter::once(node.default_version.as_str()).chain(
        config
            .workspaces
            .iter()
            .filter(|ws| ws.language == "node")
            .filter_map(|ws| ws.version.as_deref()),
    ) {
        if seen.insert(v) {
            out.push(v);
        }
    }
    out
}

fn aggregate_node_pms<'a>(
    node: &'a NodeLanguage,
    config: &'a EnvironmentConfig,
) -> Vec<&'a str> {
    let mut seen: BTreeSet<&str> = BTreeSet::new();
    let mut out: Vec<&str> = Vec::new();
    for pm in node.default_package_manager.as_deref().into_iter().chain(
        config
            .workspaces
            .iter()
            .filter(|ws| ws.language == "node")
            .filter_map(|ws| ws.package_manager.as_deref()),
    ) {
        if seen.insert(pm) {
            out.push(pm);
        }
    }
    out
}

fn emit_python_block(df: &mut String, languages: &Languages, config: &EnvironmentConfig) {
    let Some(python) = &languages.python else { return };
    let versions = aggregate_simple(&python.default_version, config, "python");
    let mut line = format!(
        "RUN PYTHON_VERSIONS=\"{}\" DEFAULT_PYTHON=\"{}\"",
        space_join(versions.iter().copied()),
        python.default_version
    );
    if let Some(idx) = &python.scip_indexer {
        line.push_str(&format!(" SCIP_INDEXER=\"{idx}\""));
    }
    line.push_str(" /tmp/djinn-scripts/install-python.sh");
    writeln!(df, "{line}").unwrap();
}

fn emit_go_block(df: &mut String, languages: &Languages, _config: &EnvironmentConfig) {
    let Some(go) = &languages.go else { return };
    // Go is intentionally single-version — multi-toolchain is handled
    // by `go install golang.org/dl/go<X>` at runtime, not at image build.
    let mut line = format!("RUN GO_VERSION=\"{}\"", go.default_version);
    if let Some(idx) = &go.scip_indexer {
        line.push_str(&format!(" SCIP_INDEXER=\"{idx}\""));
    }
    line.push_str(" /tmp/djinn-scripts/install-go.sh");
    writeln!(df, "{line}").unwrap();
}

fn emit_java_block(df: &mut String, languages: &Languages, _config: &EnvironmentConfig) {
    let Some(java) = &languages.java else { return };
    writeln!(
        df,
        "RUN JAVA_VERSION=\"{}\" /tmp/djinn-scripts/install-java.sh",
        java.default_version
    )
    .unwrap();
}

fn emit_ruby_block(df: &mut String, languages: &Languages, _config: &EnvironmentConfig) {
    let Some(ruby) = &languages.ruby else { return };
    writeln!(
        df,
        "RUN RUBY_VERSION=\"{}\" /tmp/djinn-scripts/install-ruby.sh",
        ruby.default_version
    )
    .unwrap();
}

fn emit_dotnet_block(df: &mut String, languages: &Languages) {
    let Some(d) = &languages.dotnet else { return };
    writeln!(
        df,
        "RUN DOTNET_VERSION=\"{}\" /tmp/djinn-scripts/install-dotnet.sh",
        d.default_version
    )
    .unwrap();
}

fn emit_clang_block(df: &mut String, languages: &Languages) {
    let Some(c) = &languages.clang else { return };
    writeln!(
        df,
        "RUN CLANG_VERSION=\"{}\" /tmp/djinn-scripts/install-clang.sh",
        c.default_version
    )
    .unwrap();
}

/// Build a unique, ordered list of `default_version` + all workspace
/// `version` overrides for a given language slug. Used by language
/// blocks whose workspace overrides map onto `version` rather than
/// `toolchain`.
fn aggregate_simple<'a>(
    default_version: &'a str,
    config: &'a EnvironmentConfig,
    language: &str,
) -> Vec<&'a str> {
    let mut seen: BTreeSet<&str> = BTreeSet::new();
    let mut out: Vec<&str> = Vec::new();
    for v in std::iter::once(default_version).chain(
        config
            .workspaces
            .iter()
            .filter(|ws| ws.language == language)
            .filter_map(|ws| ws.version.as_deref()),
    ) {
        if seen.insert(v) {
            out.push(v);
        }
    }
    out
}

fn emit_env(df: &mut String, config: &EnvironmentConfig) {
    for (k, v) in &config.env {
        // validate() already rejected newlines / NULs / shell-unsafe keys;
        // we still quote the value to be safe against spaces.
        writeln!(df, "ENV {k}={}", shell_quote(v)).unwrap();
    }
}

fn emit_post_build_hooks(df: &mut String, config: &EnvironmentConfig) {
    for hook in &config.lifecycle.post_build {
        emit_hook_as_run(df, hook);
    }
}

fn emit_hook_as_run(df: &mut String, hook: &HookCommand) {
    match hook {
        HookCommand::Shell(s) => {
            // Put every hook on its own `RUN`; keeps layer count
            // proportional to hook count so a single tweak invalidates
            // only the layers below it.
            writeln!(df, "RUN {s}").unwrap();
        }
        HookCommand::Exec(argv) => {
            // Build-time `RUN` in exec form is JSON-array syntax.
            writeln!(df, "RUN {}", render_json_array(argv)).unwrap();
        }
        HookCommand::Parallel(map) => {
            // Parallel at build time would need `&` + `wait`; keep it
            // simple and run sequentially. Named for log clarity.
            for (name, inner) in map {
                writeln!(df, "# hook: {name}").unwrap();
                emit_hook_as_run(df, inner);
            }
        }
    }
}

fn emit_cleanup(df: &mut String) {
    writeln!(df, "RUN rm -rf /tmp/djinn-scripts").unwrap();
}

// ---- small helpers ------------------------------------------------------

fn space_join<'a, I: IntoIterator<Item = &'a str>>(iter: I) -> String {
    let mut out = String::new();
    for (i, s) in iter.into_iter().enumerate() {
        if i > 0 {
            out.push(' ');
        }
        out.push_str(s);
    }
    out
}

fn space_join_sorted(items: &[String]) -> String {
    let mut v: Vec<&str> = items.iter().map(String::as_str).collect();
    v.sort();
    v.dedup();
    space_join(v.iter().copied())
}

fn shell_quote(value: &str) -> String {
    if value
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-' | '/' | ':' | ','))
        && !value.is_empty()
    {
        value.to_string()
    } else {
        let escaped = value.replace('"', "\\\"");
        format!("\"{escaped}\"")
    }
}

fn render_json_array(argv: &[String]) -> String {
    let parts: Vec<String> = argv
        .iter()
        .map(|s| format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\"")))
        .collect();
    format!("[{}]", parts.join(", "))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn agent_worker() -> AgentWorkerImage {
        AgentWorkerImage::new("djinn/agent-worker", "sha256-deadbeef")
    }

    fn minimal_valid_config() -> EnvironmentConfig {
        let mut cfg = EnvironmentConfig::empty();
        cfg.schema_version = djinn_stack::environment::SCHEMA_VERSION;
        cfg
    }

    #[test]
    fn empty_config_emits_base_and_worker_only() {
        let df = generate_dockerfile(&minimal_valid_config(), &agent_worker()).unwrap();
        assert!(df.dockerfile.contains("FROM debian:bookworm-slim"));
        assert!(df.dockerfile.contains("COPY --from=djinn/agent-worker:sha256-deadbeef"));
        assert!(df.dockerfile.contains("install-agent-worker.sh"));
        assert!(!df.dockerfile.contains("install-rust.sh"));
    }

    #[test]
    fn missing_worker_ref_rejected() {
        let err = generate_dockerfile(
            &minimal_valid_config(),
            &AgentWorkerImage::new("djinn/agent-worker", ""),
        )
        .unwrap_err();
        assert!(matches!(err, DockerfileError::MissingAgentWorkerRef));
    }

    #[test]
    fn two_rust_toolchains_aggregate_into_single_run_line() {
        // The motivating case: two Rust workspaces pinned to different
        // toolchains in one project.
        let mut cfg = minimal_valid_config();
        cfg.languages.rust = Some(djinn_stack::environment::RustLanguage {
            default_toolchain: "stable".into(),
            components: vec!["rust-analyzer".into()],
            targets: vec![],
        });
        cfg.workspaces = vec![
            djinn_stack::environment::Workspace {
                slug: "server".into(),
                root: "server".into(),
                language: "rust".into(),
                toolchain: Some("stable".into()),
                version: None,
                package_manager: None,
            },
            djinn_stack::environment::Workspace {
                slug: "tools-codegen".into(),
                root: "tools/codegen".into(),
                language: "rust".into(),
                toolchain: Some("1.85.0".into()),
                version: None,
                package_manager: None,
            },
        ];
        let df = generate_dockerfile(&cfg, &agent_worker()).unwrap();
        // A single RUN line with both toolchains, default preserved,
        // components carried through.
        assert!(
            df.dockerfile
                .contains("TOOLCHAINS=\"stable 1.85.0\""),
            "dockerfile:\n{}",
            df.dockerfile
        );
        assert!(df.dockerfile.contains("DEFAULT_TOOLCHAIN=\"stable\""));
        assert!(df.dockerfile.contains("COMPONENTS=\"rust-analyzer\""));
    }

    #[test]
    fn node_aggregates_workspace_versions_and_pms() {
        let mut cfg = minimal_valid_config();
        cfg.languages.node = Some(djinn_stack::environment::NodeLanguage {
            default_version: "22".into(),
            default_package_manager: Some("pnpm".into()),
            scip_indexer: None,
        });
        cfg.workspaces = vec![djinn_stack::environment::Workspace {
            slug: "legacy-ui".into(),
            root: "legacy/ui".into(),
            language: "node".into(),
            toolchain: None,
            version: Some("20".into()),
            package_manager: Some("yarn".into()),
        }];
        let df = generate_dockerfile(&cfg, &agent_worker()).unwrap();
        assert!(df.dockerfile.contains("NODE_VERSIONS=\"22 20\""));
        assert!(df.dockerfile.contains("PACKAGE_MANAGERS=\"pnpm yarn\""));
    }

    #[test]
    fn system_packages_sort_deduplicate_and_become_env_inline() {
        let mut cfg = minimal_valid_config();
        cfg.system_packages.apt = vec![
            "postgresql-client".into(),
            "jq".into(),
            "jq".into(),
            "build-essential".into(),
        ];
        let df = generate_dockerfile(&cfg, &agent_worker()).unwrap();
        assert!(df.dockerfile.contains(
            "APT_PACKAGES=\"build-essential jq postgresql-client\" /tmp/djinn-scripts/install-system.sh"
        ));
    }

    #[test]
    fn env_key_emits_env_line() {
        let mut cfg = minimal_valid_config();
        cfg.env.insert("RUST_LOG".into(), "info".into());
        cfg.env.insert("CI".into(), "true".into());
        let df = generate_dockerfile(&cfg, &agent_worker()).unwrap();
        // BTreeMap ordering is alphabetical → CI first, then RUST_LOG.
        let ci_pos = df.dockerfile.find("ENV CI=true").unwrap();
        let rust_pos = df.dockerfile.find("ENV RUST_LOG=info").unwrap();
        assert!(ci_pos < rust_pos);
    }

    #[test]
    fn post_build_hooks_emit_run_lines() {
        let mut cfg = minimal_valid_config();
        cfg.lifecycle.post_build = vec![
            HookCommand::Shell("echo build".into()),
            HookCommand::Exec(vec!["bash".into(), "-lc".into(), "echo exec".into()]),
        ];
        let df = generate_dockerfile(&cfg, &agent_worker()).unwrap();
        assert!(df.dockerfile.contains("RUN echo build"));
        assert!(
            df.dockerfile.contains(r#"RUN ["bash", "-lc", "echo exec"]"#),
            "actual:\n{}",
            df.dockerfile
        );
    }

    #[test]
    fn unknown_workspace_language_rejected() {
        let mut cfg = minimal_valid_config();
        cfg.workspaces = vec![djinn_stack::environment::Workspace {
            slug: "mystery".into(),
            root: "src".into(),
            language: "zig".into(),
            toolchain: None,
            version: None,
            package_manager: None,
        }];
        let err = generate_dockerfile(&cfg, &agent_worker()).unwrap_err();
        assert!(
            matches!(err, DockerfileError::UnknownWorkspaceLanguage(s) if s == "zig")
        );
    }

    #[test]
    fn alpine_switches_base_image_and_script() {
        let mut cfg = minimal_valid_config();
        cfg.base.distro = Distro::Alpine;
        cfg.base.variant = "3.20".into();
        let df = generate_dockerfile(&cfg, &agent_worker()).unwrap();
        assert!(df.dockerfile.contains("FROM alpine:3.20"));
        assert!(df.dockerfile.contains("/tmp/djinn-scripts/base-alpine.sh"));
    }
}
