pub mod advisory_lock;
pub mod background;
pub mod crypto;
pub mod database;
pub mod error;
pub mod launcher_compatibility;
pub mod migrations;
pub mod note_hash;
pub mod repositories;
pub mod retry;
pub mod short_id;
mod template_bootstrap;

#[cfg(any(test, feature = "test-support"))]
mod migration_150_test_support;

/// Real SQL round-trip instrumentation, sourced from `sqlx`'s own query
/// records rather than from any counter this crate maintains.
#[cfg(any(test, feature = "test-support"))]
pub mod query_observer;

#[cfg(any(test, feature = "test-support"))]
pub mod test_support {
    pub use crate::migration_150_test_support::{
        Migration150Fixture, Migration150HistoricalWrapperValues, Migration150OrdinaryPreset,
        with_migration_150_fixture,
    };
    pub use crate::query_observer::{QueryTrace, capture_queries};
    pub use crate::repositories::test_support::{
        AtomicEvidenceDemandCountsForTest, CanonicalTypedEvidenceReturnOutcomeForTest,
        DirectDeliveryMatrixCountsForTest, EvidenceDispatchRecoveryFixtureForTest,
        EvidenceDispatchRecoverySnapshotForTest, HousekeepingFixture,
        HousekeepingFixtureExpectedCounts, HousekeepingFixtureProject,
        ProjectGithubInstallationForTest, RefinementLifecycleAuditRowForTest,
        RefinementRunAuditForTest, RefinementRunReadOnlySnapshotForTest,
        StructuredEvidenceHandoffCountsForTest, TypedEvidenceDispositionFixtureForTest,
        TypedEvidenceDispositionSnapshotForTest, TypedEvidenceFindingSnapshotForTest,
        TypedEvidenceIngressFixtureForTest, TypedEvidenceRetryAuthorityForTest,
        TypedEvidenceRetryFixtureForTest, TypedEvidenceRetryScenarioForTest,
        TypedEvidenceRetrySnapshotForTest, TypedEvidenceValidationSnapshotForTest,
        UsageTestSessionSeed, UsageTestTaskSeed, activate_direct_delivery_epoch_for_test,
        activity_row_count_for_test, add_blocker_edge, apply_all_migrations_to_fresh_database,
        atomic_evidence_demand_counts_for_test, backdate_coordinator_incarnation_lease,
        backdate_task_attempt_created_at, backdate_task_updated_at,
        build_multi_project_housekeeping_fixture, ci_route_age_calling_for_test,
        ci_route_age_reserved_for_test, ci_route_force_calling_owner_for_test,
        ci_route_lease_count_for_test, ci_route_plant_reserved_for_test,
        ci_route_row_count_for_test, close_evidence_dispatch_task_for_test, close_task_at,
        complete_refinement_intent_without_successor_for_test,
        correlate_task_to_refinement_run_for_test, corrupt_credential_encrypted_value,
        corrupt_refinement_task_role_for_test, count_rows_for_test,
        delete_proposal_lint_result_for_revision_for_test, delete_proposal_lint_results_for_test,
        delete_session_row, direct_delivery_matrix_counts_for_test,
        disable_direct_delivery_epoch_for_test, dispose_typed_evidence_validation_for_test,
        drop_table_cascade_for_test, drop_table_for_test,
        elapse_refinement_run_wall_clock_for_test, ensure_doctor_findings_schema,
        equalize_note_temporal_signals_for_test, event_bus_for,
        evidence_dispatch_recovery_snapshot_for_test, force_refinement_run_park_kind_for_test,
        force_refinement_run_terminal_for_test, inject_residual_session_after_settlement_for_test,
        insert_pending_attempt_with_raw_owner, liveness_evidence_for_task_for_test,
        make_coordinator_incarnation_error_after_first_read,
        make_coordinator_incarnation_vanish_after_first_read, make_project,
        make_refinement_run_phantom_for_test,
        materialize_evidence_dispatch_recovery_fixture_for_test,
        materialize_judge_authority_for_test,
        materialize_typed_evidence_disposition_fixture_for_test,
        materialize_typed_evidence_retry_fixture_for_test, model_turn_accounting_fixture,
        model_turn_decision_count_fixture, model_turn_decision_fixture,
        model_turn_launch_identities_fixture, model_turn_lease_heartbeat_snapshot_fixture,
        model_turn_lease_lifecycle_fixture, model_turn_lease_owner_pod_uid_fixture,
        model_turn_request_lifecycle_fixture, model_turn_terminal_fixture,
        nullify_note_confidence_for_test, override_debate_trail_body_metadata,
        pending_feedback_disposition_counts_for_test, persist_project_github_installation_for_test,
        proposal_lint_revision_id_for_test, queue_feedback_refinement_generation_for_test,
        refinement_run_audit_for_test, refinement_run_read_only_snapshot_for_test,
        reject_atomic_demand_debate_inserts_for_test, reject_ci_route_attempt_updates_for_test,
        reject_evidence_findings_debates_for_test, reject_evidence_projection_inserts_for_test,
        reject_interrupted_session_for_test, reject_new_task_arbitrations_for_test,
        reject_refinement_successor_for_test, reject_refinement_terminal_audit_for_test,
        reject_task_liveness_evidence_for_test, remove_direct_delivery_epoch_for_test,
        rename_note_confidence_column_for_test, replace_legacy_proposal_head_for_test,
        restore_active_direct_delivery_epoch_for_test, seed_board_health_mismatch_candidate,
        seed_breaker_open_dispatch_state, seed_canonical_typed_evidence_ingress_fixture_for_test,
        seed_chat_session_row, seed_direct_delivery_proposal_for_test,
        seed_direct_delivery_proposal_owner_for_test, seed_legacy_launcher_authority_for_test,
        seed_model_turn_admission_fixture, seed_project, seed_rate_limited_dispatch_state,
        seed_readiness_detail_projection_for_test, seed_session_row, seed_session_row_with_id,
        seed_stale_typed_evidence_disposition_for_test, seed_task_row,
        seed_typed_evidence_ingress_fixture_for_test, seed_unknown_direct_delivery_epoch_for_test,
        seed_workspace_coverage_for_test, set_model_turn_capability_fixture,
        set_model_turn_phase_fixture, set_proposal_author_for_test, set_task_short_id_for_test,
        set_typed_evidence_disposition_lifecycle_for_test,
        structured_evidence_handoff_counts_for_test, switch_to_adversary_authority_for_test,
        switch_to_advocate_authority_for_test, switch_to_judge_authority_for_test,
        task_attempt_count_for_test, task_row_count_for_test, task_status_for_test,
        typed_evidence_disposition_snapshot_for_test, typed_evidence_finding_snapshot_for_test,
        typed_evidence_retry_snapshot_for_test,
        typed_evidence_transition_count_for_validation_for_test,
        typed_evidence_validation_snapshot_for_finding_for_test,
        typed_evidence_validation_snapshot_for_test,
    };
}

pub use database::{
    Database, DatabaseBackendCapabilities, DatabaseBackendKind, DatabaseBootstrapInfo,
    DatabaseConnectConfig, NoteSearchBackend, NoteVectorBackend, PostgresDatabaseConfig,
    SqliteVecStatus, default_db_path, test_database_base_url,
};
pub use error::{DbError as Error, DbResult as Result, SpecLintRejected, SpecLintViolation};
pub use launcher_compatibility::{
    AdmissionDecision, AdmissionRejection, InventoryFault, LegacyDigestInventory,
    PreProtocolDigest, admit_with_legacy_inventory, decide_admission,
};
#[cfg(any(test, feature = "test-support"))]
pub use repositories::repo_graph_generation::ReservedPublicationFailureStage;
pub use repositories::tool_call_evaluator::{
    Decision, EvalInput, GateResult, GateThresholds, GoStopReport, ManualAuditResult, SampleMinima,
    WindowSpec, evaluate, matched_baseline_rows,
};
pub use repositories::tool_call_export::{
    ExportDimensions, NormalizedToolCallRow, PersistedTranscript, ToolCallExportRepository,
    normalize_persisted_transcript,
};
pub use repositories::tool_call_metrics::{
    AdoptionCounts, AdoptionShare, ConfidenceInterval, FailureRates, RateMetric,
    ToolSurfaceMetrics, adoption_counts, apply_patch_adoption_share, compute_metrics,
    edit_minus_apply_patch_failure_interval, failure_rates, read_truncation_loop_rate,
    retry_after_edit_failure, wilson_difference_interval, wilson_interval,
};
pub use repositories::{
    agent::{
        AgentCreateInput, AgentListQuery, AgentListResult, AgentMetrics, AgentRepository,
        AgentUpdateInput, VALID_BASE_ROLES,
    },
    audit_sampler::{
        AuditOutcomeKind, AuditOutcomeReportRow, AuditOutcomeRow, AuditSamplerRepository,
        AuditStratum, CreateSampleFrameParams, CreateSamplePolicyParams, CreateSelectionParams,
        MergedChangeRow, RecordOutcomeParams, SampleFrameRow, SamplePolicyRow, SelectionRow,
        UnmaterializedSelection, UpsertMergedChangeParams,
    },
    build_admission_denial::{BuildAdmissionDenialRecord, BuildAdmissionDenialRepository},
    build_lease::{
        BuildLeaseConsumerKind, BuildLeaseKey, BuildLeaseRepository, BuildLeaseRow,
        BuildLeaseSnapshot, BuildLeaseState, BuildLeaseTerminalReason, GrantNextBuildLeaseResult,
        QueueBuildLeaseInput, QueueBuildLeaseResult, ReclaimAbsentBuildLeaseInput,
        ReclaimAbsentBuildLeaseOutcome,
    },
    build_pod_permit::{
        AcquireBuildPodPermitResult, BindBuildPodPermitResult, BuildPodPermitRepository,
        BuildPodPermitRow, BuildPodPermitState, BuildPodResizeIdentity,
        CaptureBuildPodResizeIdentityResult, ReleaseBuildPodPermitResult,
        TransitionBuildPodResizeLifecycleResult,
    },
    chat_interruption_notice::{
        ChatInterruptionNotice, ChatInterruptionNoticeRepository, CreateChatInterruptionNotice,
    },
    ci_incomplete_hold::{
        CI_INCOMPLETE_HOLD_MAX_POLLS, CiHoldApply, CiHoldEscalationRoute, CiHoldIdentity,
        CiHoldObservation, CiHoldReservation, CiHoldStreak, CiIncompleteHoldRepository,
    },
    ci_route_attempt::{
        CI_CALLING_RECOVERY_TIMEOUT_SECS, CI_HEAD_BUDGET_LIMIT,
        CI_RESERVATION_RECOVERY_TIMEOUT_SECS, CI_SIGNATURE_BUDGET_LIMIT, CiAction, CiActionPhase,
        CiBudgetCounts, CiCallingRecovery, CiCallingRecoveryAuthority, CiCallingRecoveryReason,
        CiCallingRecoveryRecord, CiChargeOutcome, CiClass, CiDiagnosticReason, CiEvidenceIdentity,
        CiLane, CiLeadRejection, CiLeadSessionAttachment, CiOriginState, CiQuiescenceProof,
        CiReopenMode, CiReserveOutcome, CiReservedRecovery, CiRouteAttempt,
        CiRouteAttemptRepository, CiRouteOutcome, CiRouteQuiescence, CiRouteReservation,
        CiRouteSubject, CiSubjectKind, CiTier2LeaseOutcome, CiTier2LeaseState, CiTier2Reason,
        CiTier2Resolution,
    },
    ci_route_report::{
        CiRollbackQuiescenceReport, CiRouteQuiescenceAttestation, CiRouteReport,
        CiRouteReportFilter,
    },
    code_chunk::{
        ChunkAndEmbedReport, CodeChunk, CodeChunkEmbeddingProvider, CodeChunkRepairEmbeddingRow,
        CodeChunkRepository, CodeChunkSearchHit, CodeChunkVectorBackend, CodeChunkVectorMatch,
        CodeChunkVectorStore, EmbeddedCodeChunk, InflightGuard, NoopCodeChunkVectorStore,
        QdrantCodeChunkConfig, QdrantCodeChunkVectorStore, UpsertCodeChunkEmbedding, cap_per_file,
        chunk_and_embed_files, hydrate_chunk_ids, lexical_search_chunks,
        qdrant_code_chunk_point_id_hex, try_claim_project,
    },
    commit_file_changes::{
        CommitFileChange, CommitFileChangeRepository, CoupledFile, CoupledPair, CouplingHub,
        CouplingPairEvent, FileChurn, MAX_FILES_PER_COMMIT_FOR_PAIRS, coupling_event_key,
        derive_pair_events, derive_pair_events_into,
    },
    coordinator_incarnation::{CoordinatorIncarnation, CoordinatorIncarnationRepository},
    credential::CredentialRepository,
    custom_provider::CustomProviderRepository,
    direct_delivery_capability::{
        DirectDeliveryCapabilityRepository, DirectDeliverySchemaCapability,
    },
    dispatch_pause::{DispatchPauseMutation, DispatchPauseRepository, DispatchPauseTarget},
    dispatch_state::{DispatchStateRecord, DispatchStateRepository, DispatchStateUpsert},
    doctor_finding::{
        DeduplicatedDoctorFindingInsert, DoctorFinding, DoctorFindingRepository,
        MAX_RECENT_FINDINGS, NewDoctorFinding, RecentDoctorFindings, severity as doctor_severity,
    },
    epic::{
        EpicBlockerRef, EpicCountQuery, EpicCreateInput, EpicListQuery, EpicListResult,
        EpicRepository, EpicTaskCounts, EpicUpdateInput,
    },
    events::EventsRepository,
    evidence::{
        AppendEvidenceInvocation, EvidenceRepository, InsertEvidenceFinalizedProjection,
        InsertEvidencePlan, InsertEvidencePlanCheck,
    },
    extension_load_diagnostic::{ExtensionLoadDiagnosticRepository, InsertExtensionLoadDiagnostic},
    git_settings::GitSettingsRepository,
    image::{
        CurrentBuildTransition, Image, ImageRepository, ImageStatus, PreProtocolImage,
        SelectedCatalogImage,
    },
    invocation_lease_authority::{
        InvocationLeaseAuthorityRepository, InvocationLeaseAuthorityRow, InvocationLeaseMode,
    },
    kueue_workload_admission::{
        AdmissionApplied, KueueWorkloadAdmissionRecord, KueueWorkloadAdmissionRepository,
    },
    launcher_authority_mode::{
        LauncherAuthorityDrainCensus, LauncherAuthorityModeRepository, LauncherAuthorityModeRow,
        LauncherProtocolAdmission, SetLauncherAuthorityModeResult,
        decide_launcher_protocol_admission,
    },
    legacy_settings_import::{
        LegacySettingsImport, LegacySettingsImportError, LegacySettingsImportResult,
    },
    liveness::{
        ClaimExtensionRecord, CurrentLivenessState, LivenessEvidenceSnapshot, LivenessRepository,
    },
    llm_call_attempt::{
        CreateLlmCallAttemptParams, FinalizeLlmCallAttemptParams, LlmCallAttemptRecord,
        LlmCallAttemptRepository, LlmCallOutcome,
    },
    model_turn_admission::{
        MODEL_TURN_ADMISSION_SCHEMA_VERSION, ModelTurnAcquireInput, ModelTurnAcquireOutcome,
        ModelTurnAcquireTurnInput, ModelTurnAdmissionPhase, ModelTurnAdmissionRejection,
        ModelTurnAdmissionRepository, ModelTurnAdmissionSchemaReadiness, ModelTurnAdmissionWait,
        ModelTurnAuthoritativeUsage, ModelTurnBucketBinding, ModelTurnBucketDebit,
        ModelTurnBucketKind, ModelTurnCapabilityHeartbeatInput, ModelTurnCapabilityState,
        ModelTurnControllerWindow, ModelTurnControllerWindowDiagnostic,
        ModelTurnControllerWindowDiagnosticCode, ModelTurnControllerWindowInput,
        ModelTurnControllerWindowSummary, ModelTurnDecisionDiagnostic, ModelTurnDecisionKind,
        ModelTurnDecisionRecordInput, ModelTurnIdentityState, ModelTurnLearnerWindow,
        ModelTurnLease, ModelTurnLeaseExpiryInput, ModelTurnLeaseIdentity, ModelTurnLeaseLifecycle,
        ModelTurnLeaseMutationOutcome, ModelTurnLeaseReconciliationInput,
        ModelTurnLeaseTerminalOutcome, ModelTurnObservation, ModelTurnPhaseCEvidence,
        ModelTurnPhaseCEvidenceInput, ModelTurnPhaseCEvidenceOutcome, ModelTurnPhaseCEvidenceStage,
        ModelTurnPool, ModelTurnReservation, ModelTurnReservationBucket, ModelTurnReservationState,
    },
    models::ModelsRepository,
    note::{
        AnchorProposerKind, BackfillRetrievalAnchorOptions, BackfillRetrievalAnchorReport,
        BoundedCluster, BoundedClusteringOutcome, CONSOLIDATION_ATTEMPT_VERSION,
        CONSOLIDATION_BACKFILL_BATCH_ROWS, CONSOLIDATION_CANONICAL_TAG,
        CONSOLIDATION_DEFAULT_SCORE_THRESHOLD, CONSOLIDATION_ELIGIBLE_NOTE_TYPES,
        CONSOLIDATION_MAX_ADMISSION_COMPARISONS, CONSOLIDATION_MAX_CLUSTER_SOURCES,
        CONSOLIDATION_MAX_PARTITION_INPUTS, CONSOLIDATION_MIN_CLUSTER_SOURCES, CONTRADICTION,
        CommitConsolidationCanonical, CommittedConsolidationCanonical, ConsolidatedNoteProvenance,
        ConsolidationAttemptWitness, ConsolidationCandidateEdge, ConsolidationCluster,
        ConsolidationCommitOutcome, ConsolidationConflict, ConsolidationConflictReason,
        ConsolidationNote, ConsolidationPartitionKey, ConsolidationRunMetric,
        ConsolidationWriteBoundary, ContradictionCandidate, CreateCanonicalConsolidatedNote,
        CreateConsolidationRunMetric, CreatedCanonicalConsolidatedNote, DbNoteGroup,
        DirectedScoreRow, EligibleEmbeddingNote, EligibleSourceSelection, EmbeddedNote,
        EmbeddingAssociationRefreshStats, EmbeddingCandidate, LexicalSearchBackend,
        LexicalSearchMode, LexicalSearchPlan, LlmAnchorProposer, MemoryEntityAssociation,
        MemoryEntityKind, MemoryEntityRef, MemoryEntityType, NoopNoteVectorStore,
        NoteAccessAttribution, NoteAccessEvent, NoteAccessSource, NoteAssociationEntry,
        NoteAssociationKind, NoteAssociationProvenanceRow, NoteAssociationProvenanceUpsert,
        NoteAssociationSource, NoteConsolidationRepository, NoteDedupCandidate, NoteEmbeddingMatch,
        NoteEmbeddingProvider, NoteEmbeddingRecord, NoteQualityAssessment, NoteRepairEmbeddingRow,
        NoteRepository, NoteRevisionActorKind, NoteRevisionCreateState, NoteRevisionDesiredState,
        NoteRevisionEvent, NoteRevisionEventInput, NoteRevisionEventKind, NoteRevisionEventRow,
        NoteRevisionMutation, NoteRevisionMutationResult, NoteRevisionReason, NoteRevisionSnapshot,
        NoteRevisionSubsystem, NoteRevisionUpdateState, NoteRevisionValidationError,
        NoteSearchParams, NoteStatus, NoteSupersedesAssociation, NoteVectorStore,
        PartitionPressureMetric, PersistWorkingSpecRequest, PersistedWorkingSpec,
        PromoteWorkingSpecSection, PromotedWorkingSpecNote, PromptBudgetReport,
        ProposedBackfillAnchor, ProvenanceBackfillReport, QdrantConfig, QdrantNoteVectorStore,
        QueryReplayReport, REVISION_PAGE_MAX, RankingReport, ReplayCriteria, ReplayFixture,
        ReplayNote, ReplayQuery, ReplayReport, RevisionCursor, RevisionCursorError,
        RevisionHistoryPage, RevisionLookupRequest, RevisionRangeRequest, STALE_CITATION,
        STALE_DECAY_SIGNAL, SessionRevisionPage, SessionRevisionRequest,
        TrustedNoteRevisionAttribution, TrustedNoteRevisionProvenance, UpsertNoteEmbedding,
        WORKING_SPEC_CONSTRAINT_SENTENCE, WORKING_SPEC_TAG, anchor_embedding_replay_fixture,
        assess_note_quality, build_bounded_clusters, build_lexical_search_plan,
        cluster_source_id_set, clusters_are_disjoint, connected_components_from_score_matrix,
        consolidation_attempt_id, decay_signal_for_elapsed_days, embedding_content_hash,
        embedding_document_text, executable_lexical_search_sql, folder_for_type,
        folder_for_type_with_status, generate_anchor_embedding_replay_report,
        infer_embedding_branch_from_worktree, infer_note_type, is_consolidation_eligible_note_type,
        is_singleton, legacy_embedding_document_text, lexical_search_threshold, looks_task_local,
        minimum_valid_score_threshold, normalize_lexical_score, normalize_virtual_note_path,
        note_access_events_for_note, permalink_for, permalink_for_with_status,
        permalink_from_virtual_note_path, propose_anchor_deterministic,
        render_anchor_embedding_replay_report_markdown, render_note_markdown, required_sections,
        rrf_fuse, sanitize_postgres_tsquery, sanitize_sqlite_fts5_query, slugify, task_branch_name,
        title_from_permalink, validate_postgres_tsvector_threshold,
        virtual_note_path_for_permalink, working_spec_permalink, working_spec_title,
    },
    oauth::{
        AuthorizationCode, McpAccessToken, NewAccessToken, NewAuthorizationCode, NewOAuthClient,
        OAuthClient, OAuthRepository,
    },
    org_ai_policy::OrgAiPolicyRepository,
    org_config::{NewOrgConfig, OrgConfig, OrgConfigRepository},
    project::{
        DispatchImage, ProjectConfig, ProjectDispatchReadiness, ProjectImage, ProjectImageStatus,
        ProjectRepository,
    },
    project_live_state_migration::{
        BeginProjectLiveStateMigration, MigrationKey, ProjectLiveStateMigration,
        ProjectLiveStateMigrationRepository, RESULT_FAILED, RESULT_PENDING, RESULT_ROLLED_BACK,
        RESULT_SUCCEEDED,
    },
    project_workspace_coverage::{
        COVERAGE_STATUS_EXCLUDED, COVERAGE_STATUS_INDEXED, COVERAGE_STATUS_INDEXER_FAILED,
        COVERAGE_STATUS_TIMED_OUT, COVERAGE_STATUS_UNSUPPORTED_LANGUAGE, ProjectWorkspaceCoverage,
        ProjectWorkspaceCoverageRepository, ProjectWorkspaceCoverageUpsert, coverage_status_is_gap,
    },
    project_workspace_graph::{
        CODELESS_WORKSPACE_SLUG, ProjectWorkspaceGraph, ProjectWorkspaceGraphLatest,
        ProjectWorkspaceGraphRepository, ProjectWorkspaceGraphUpsert,
    },
    proposal::{
        ActiveEvidenceAuthorityTask, AtomicEvidenceDemandInput, AtomicEvidenceDispositionInput,
        AtomicEvidenceDispositionResult, AtomicEvidenceRetryInput, AtomicEvidenceRetryResult,
        AwaitingReviewPark, FeedbackRefinementDisposition, FeedbackRefinementDispositionInput,
        FeedbackRefinementRejectionInput, FeedbackRefinementRejectionResult,
        NeedsEvidenceCapStatus, NeedsEvidenceClaimLink, ProposalCreateInput,
        ProposalDebateTrailCreateInput, ProposalFeedbackCreateInput, ProposalListQuery,
        ProposalListResult, ProposalListSummaryRow, ProposalMemoryRef, ProposalRef,
        ProposalRepository, ProposalUpdateInput,
    },
    proposal_build_attempt::{
        AcquireProposalBuildAttemptLeaseInput, AcquireProposalBuildAttemptLeaseResult,
        ActivateProposalBuildAttemptInput, ActivateProposalBuildAttemptResult,
        PersistAttemptPrIdentityInput, PersistAttemptPrIdentityResult, ProposalBuildAttemptLease,
        ProposalBuildAttemptRepository, ReconcileAttemptBranchHeadInput,
        ReconcileAttemptBranchHeadResult, ReserveProposalBuildAttemptInput,
        ReserveProposalBuildAttemptResult, ResolveTaskActiveAttemptResult,
        RetireProposalBuildAttemptInput, RetireProposalBuildAttemptResult, TaskActiveBuildAttempt,
    },
    proposal_integrity::{
        LintMaterializationOutcome, MAX_PROPOSAL_INTEGRITY_PAGE_SIZE, ProposalIntegrityHead,
        ProposalIntegrityHeadPage, ProposalIntegrityRepository,
    },
    readiness::{
        CreateReadinessAreaAttempt, CreateReadinessCompositionArea, CreateReadinessRun,
        MaterializeReadinessKickoff, NewReadinessEvent, NewReadinessFinding,
        NewReadinessSuggestion, ReadinessAggregation, ReadinessAreaAttemptRow,
        ReadinessAreaResultCallback, ReadinessAreaScoreRow, ReadinessCallbackOutcome,
        ReadinessCompositionAreaRow, ReadinessGuardrailFindingRow, ReadinessGuardrailStatus,
        ReadinessKickoffMaterialization, ReadinessProjectScoreRow,
        ReadinessRemediationSuggestionRow, ReadinessRepository, ReadinessRunDetail,
        ReadinessRunEventRow, ReadinessRunRow, RetryReadinessAreaAttempt, readiness_area_score,
        readiness_project_score, readiness_score_band, readiness_severity_weight,
    },
    refinement_feedback_handoff_observation::{
        FeedbackRefinementActiveBoundary, FeedbackRefinementAdmittedState,
        FeedbackRefinementLifecycleState, PendingFeedbackRefinementState,
    },
    refinement_run::{
        AcknowledgeRefinementTaskMaterializationRequest, ActiveRefinementRun,
        AdmitRefinementRunRequest, ClaimRefinementIntentRequest, CompleteRefinementIntentRequest,
        LoadRefinementRunSnapshotRequest, ParkRefinementRunFromIntentRequest,
        ParkRefinementRunRequest, RefinementAdmissionError, RefinementAdmissionOutcome,
        RefinementAdmissionSource, RefinementDurableProgress, RefinementIntentLease,
        RefinementIntentMutationError, RefinementLifecycleAggregate, RefinementNextIntent,
        RefinementPendingIntent, RefinementRunAggregate, RefinementRunSnapshotError,
        RefinementRunSnapshotResult, RefinementStalledHandoff, ReleaseRefinementIntentClaimRequest,
        ResolveRefinementHumanReviewRequest, SourceIntentTransitionRequest,
        TerminalRefinementRunFromIntentRequest, TerminalRefinementRunRequest,
        is_refinement_stalled_handoff,
    },
    repo_graph_cache::{CachedRepoGraph, RepoGraphCacheInsert, RepoGraphCacheRepository},
    repo_graph_generation::{
        CurrentGalaxyArtifact, GENERATION_STREAM_PIN_LOCK_CLASS, GenerationStreamPinKey,
        MAX_GALAXY_ARTIFACT_BYTES, MAX_GALAXY_ARTIFACT_CHUNKS, MAX_GALAXY_CHUNK_BYTES,
        PinnedGalaxyArtifact, PinnedGalaxyArtifactMetadata, PinnedGalaxyArtifactSelection,
        ProjectCurrentGraph, RepoGraphGalaxyArtifact, RepoGraphGalaxyArtifactInsert,
        RepoGraphGalaxyChunk, RepoGraphGalaxyChunkInsert, RepoGraphGeneration,
        RepoGraphGenerationRepository, ReservedGalaxyArtifactChunk, ReservedGalaxyArtifactManifest,
        ReservedGraphPublication, SUPPORTED_GALAXY_ARTIFACT_ENCODING,
        SUPPORTED_GALAXY_ARTIFACT_VERSION, acquire_generation_stream_pin_shared,
        generation_stream_pin_key, release_generation_stream_pin_exclusive,
        release_generation_stream_pin_shared, try_acquire_generation_stream_pin_exclusive,
    },
    repo_graph_retention::{
        DEFAULT_RETENTION_HISTORY_N, MAX_RETENTION_BATCH, MIN_RETENTION_HISTORY_N,
        RepoGraphRetentionRepository, RetentionMode, RetentionSkipClass, RetentionSweepOutcome,
        RetentionSweepRequest,
    },
    run_dirs::{
        ReconciledRunDirInput, ReserveRunDirInput, RunDirKey, RunDirRepository, RunDirRow,
        RunDirState, RunDirStateTotals,
    },
    scip_indexer_timing::{
        ScipIndexerTiming, ScipIndexerTimingObservation, ScipIndexerTimingRepository,
        TIMING_STATUS_FAILED, TIMING_STATUS_SUCCESS, TIMING_STATUS_TIMED_OUT,
    },
    service::{ServicePreset, ServicePresetRepository},
    session::{
        AutonomousSessionOutcomeRow, CreateSessionParams, CreateTaskExecutionSessionParams,
        ExtractionBackfillCandidate, OrphanSessionCandidate, SessionRepository,
        SessionStatusSnapshot,
    },
    session_auth::{CreateUserAuthSession, SessionAuthRepository, UserAuthSessionRecord},
    session_compaction_boundary::{
        BeginCompactionParams, CompactionBoundary, CompactionPhase, CompactionTrigger,
        CompleteCompactionParams, SessionCompactionBoundaryRepository,
    },
    session_message::SessionMessageRepository,
    settings::SettingsRepository,
    task::TaskRepository,
    task::{
        ActivityQuery, BlockerRef, BoardHealthMismatchCandidate, ChildDisposition, CountQuery,
        CreateTaskInProjectParams, CreateTaskParams, DeliveryFinalizeInput,
        DeliveryMappedHeadRetryInput, DeliveryPrepareInput, DeliveryReworkInput,
        DeliveryTransitionResult, DispositionCounts, DispositionFinding, DispositionPlan,
        DispositionScope, EffectiveCreatorProvenance, ListQuery, ListResult, ReadyQuery,
        TaskIntegrationResult, UpdateTaskParams, evaluate_board_health_mismatch_candidate,
    },
    task_arbitration::{
        ArbitrationState, CreateArbitrationParams, TaskArbitrationRecord,
        TaskArbitrationRepository, TryCreateResult, UpdateDispatchLedgerParams,
    },
    task_attempt::{
        CompletedParentSummary, CreateTaskAttemptParams, DispatchGroupTerminalEvidence,
        DispatchGroupTerminalization, FillTaskAttemptParams, GuardAdoptedPrTaskAttemptParams,
        GuardDeferTaskAttemptParams, OrphanedPendingAttempt, ReworkMarkerTaskAttemptParams,
        SubmitTaskAttemptParams, TaskAttemptRepository, TerminalTaskAttemptParams,
    },
    task_run::{CreateTaskRunParams, TaskRunRepository},
    typed_evidence::{
        AllocateTypedEvidenceAttemptInput, AllocateTypedEvidenceRetryInput,
        AppendTypedEvidenceTransitionInput, DemandTypedEvidenceInput,
        DemandedTypedEvidenceDispatch, DispatchTypedEvidenceDemandInput,
        DispatchTypedEvidenceRetryInput, DisposeTypedEvidenceInput, LegacyEvidenceParityProjection,
        PersistTypedEvidenceValidationInput, PlannedTypedEvidenceCheckInput,
        TerminalTypedEvidenceReturnDelivery, TribunalEvidenceReturnAnchorV1,
        TribunalEvidenceReturnCheckV1, TribunalEvidenceReturnFailureV1,
        TribunalEvidenceReturnFindingV1, TribunalEvidenceReturnGapV1,
        TribunalEvidenceReturnResultV1, TribunalEvidenceReturnV1, TypedEvidenceAttemptAllocation,
        TypedEvidenceBackfillReport, TypedEvidenceDemandDispatchErrorInput,
        TypedEvidenceDispositionProjection, TypedEvidenceFindingProjection,
        TypedEvidenceLifecycleProjection, TypedEvidenceRepository,
        TypedEvidenceRetryDispatchErrorInput, legacy_demand_hash, normalized_demand_hash,
    },
    usage_analytics::{
        EntityBreakdownRow, GroupDimension, ModelEffectivenessRow, ProjectModelMatrixRow,
        SeriesDetailRow, UsageAnalyticsQuery, UsageAnalyticsRepository, UsageTotals,
    },
    user::{User, UserRepository},
    user_settings::UserSettingsRepository,
    warm_base_activity::{WarmBaseActivity, WarmBaseActivityRepository},
    warm_graph_attempt::{
        MAX_WARM_GRAPH_ATTEMPT_DETAIL_CHARS, WarmGraphAttempt, WarmGraphAttemptRepository,
        WarmGraphAttemptStatus, WarmGraphOutcome,
    },
};
pub use short_id::{ResolvedEntity, resolve_short_ids};
