ALTER TABLE notes ADD COLUMN access_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE notes ADD COLUMN confidence REAL NOT NULL DEFAULT 1.0;
ALTER TABLE notes ADD COLUMN abstract TEXT;
ALTER TABLE notes ADD COLUMN overview TEXT;
