#!/usr/bin/env perl
# Production-image memory-sustainability workload driver.
use strict; use warnings;
use Getopt::Long qw(GetOptions); use JSON::PP; use HTTP::Tiny; use Time::HiRes qw(time sleep);
use File::Path qw(make_path); use File::Basename qw(dirname); use File::Copy qw(move);
my $SCHEMA='memory-sustainability-raw/v1'; my $GIB4=4*1024*1024*1024;
my @METRICS=qw(djinn_process_rss_bytes djinn_process_anon_rss_bytes djinn_jemalloc_allocated_bytes djinn_jemalloc_resident_bytes djinn_jemalloc_retained_bytes djinn_canonical_graph_slot_present djinn_canonical_graph_slot_approx_serialized_bytes djinn_canonical_graph_slot_node_count djinn_canonical_graph_slot_edge_count);
my $here=__FILE__; $here =~ s{/[^/]+$}{};
my %o=(manifest=>"$here/../fixtures/manifest.json",profile=>'production',t0_seconds=>1800,t1_seconds=>900,burst_seconds=>7200,t2_seconds=>300,board_tick_seconds=>300,request_count=>100,cgroup_root=>'/sys/fs/cgroup',token_env=>'DJINN_GALAXY_TOKEN');
GetOptions(\%o,'manifest=s','profile=s','output=s','metrics-url=s','galaxy-url=s','token-env=s','cgroup-root=s','install-command=s','board-command=s','generation-command=s','restart-command=s','fixture-command=s','t0-seconds=f','t1-seconds=f','burst-seconds=f','t2-seconds=f','board-tick-seconds=f','request-count=i','fake!') or die "invalid options\n";
for my $key (qw(t0 t1 burst t2 board_tick request)) { my $dash=$key; $dash =~ s/_/-/g; my $source=$dash . ($key eq 'request' ? '-count' : '-seconds'); my $target=$key . ($key eq 'request' ? '_count' : '_seconds'); $o{$target}=$o{$source} if exists $o{$source}; }
$o{'metrics-url'} //= $ENV{DJINN_METRICS_URL}; $o{'galaxy-url'} //= $ENV{DJINN_GALAXY_URL};
$o{'install-command'} //= $ENV{DJINN_GRAPH_INSTALL_COMMAND}; $o{'board-command'} //= $ENV{DJINN_BOARD_SCAN_COMMAND}; $o{'generation-command'} //= $ENV{DJINN_GRAPH_GENERATION_COMMAND}; $o{'restart-command'} //= $ENV{DJINN_RESTART_COUNTER_COMMAND}; $o{'fixture-command'} //= $ENV{DJINN_FIXTURE_INSPECTION_COMMAND};
die "--output is required\n" unless $o{output}; die "unknown profile\n" unless $o{profile}=~/^(production|smoke)$/;
die "durations must be nonnegative and request count positive\n" if grep {$o{$_}<0} qw(t0_seconds t1_seconds burst_seconds t2_seconds board_tick_seconds) or $o{request_count}<1;
die "metrics URL, galaxy URL, and nonempty token environment variable are required\n" unless $o{fake} || ($o{'metrics-url'} && $o{'galaxy-url'} && $ENV{$o{token_env}});
open my $mf,'<:raw',$o{manifest} or die "manifest: $!\n"; local $/; my $manifest=decode_json(<$mf>); close $mf;
die "invalid fixture manifest\n" unless $manifest->{schema} eq 'memory-sustainability-fixtures/v1' && $manifest->{profiles}{$o{profile}}; my $profile=$manifest->{profiles}{$o{profile}};
make_path(dirname($o{output})); my $partial="$o{output}.partial"; sysopen(my $raw,$partial,65|128) or die "refusing to overwrite evidence $partial: $!\n"; my $json=JSON::PP->new->canonical(1); my @fake_restarts=split /,/, ($ENV{DJINN_FAKE_RESTARTS}//'0'); my $fake_restart_read=0;
sub emit { my($kind,%x)=@_; print $raw $json->encode({schema=>$SCHEMA,kind=>$kind,timestamp=>scalar(gmtime()).'Z',timestamp_unix_ms=>int(time()*1000),%x})."\n"; $raw->flush; }
sub fail { die "memory workload failed: $_[0]\n" }
sub number { my($x,$what)=@_; fail("$what is not numeric") unless defined $x && $x =~ /^-?(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?$/i; 0+$x }
sub fake_fixture { $json->encode({seed=>$profile->{seed},checksums=>$profile->{checksums},graph=>$profile->{graph},board_health=>$profile->{board_health},galaxy_artifact=>$profile->{galaxy_artifact}}) }
sub cmd_json { my($cmd,$what)=@_; my $out; if($o{fake}){$out=$what eq 'fixture'?fake_fixture():$what eq 'board'?'{"pages":40}':$what eq 'restart'?'{"restarts":'.($fake_restarts[$fake_restart_read++]//$fake_restarts[-1]).'}':$what eq 'generation'?'{"generation":"fake-generation-v1"}':'{"warm_peak_bytes":1100000000,"server_peak_bytes":1200000000}'}else{fail("required $what command was not supplied") unless $cmd; $out=`$cmd 2>&1`; fail("$what command failed") if $?} $out =~ s/^\s+|\s+$//g; my $v=eval {decode_json($out)}; fail("$what command must emit a JSON object") unless $v && ref $v eq 'HASH'; $v }
sub cgroup_from_text { my($limit,$current,$events)=@_; chomp($limit,$current); fail('cgroup memory.max is not numeric') unless $limit=~/^\d+$/; fail('cgroup memory.current is not numeric') unless $current=~/^\d+$/; my %e; for(split /\n/,$events){next if /^\s*$/; my($k,$v)=split /\s+/; fail('malformed cgroup memory.events') unless defined $k && defined $v && $k=~/^\w+$/ && $v=~/^\d+$/; $e{$k}=0+$v} for(qw(oom oom_kill)){fail("cgroup memory.events missing $_") unless exists $e{$_}} (0+$limit,0+$current,\%e) }
sub cgroup { if($o{fake}){my $bad=$ENV{DJINN_FAKE_MALFORMED}||''; return cgroup_from_text("$GIB4\n",$bad eq 'cgroup'?"nope\n":"1000000000\n",$bad eq 'events'?"oom nope\n":"oom 0\noom_kill 0\n")} my $r=$o{cgroup_root}; my($a,$b,$c); for my $f (qw(memory.max memory.current memory.events)){open my $h,'<',"$r/$f" or fail('unreadable cgroup v2 signals'); if($f eq 'memory.max'){$a=<$h>}elsif($f eq 'memory.current'){$b=<$h>}else{local $/; $c=<$h>}close $h} cgroup_from_text($a,$b,$c) }
sub fake_metrics_text { my($installed)=@_; my $g=$profile->{graph}; my %m=(djinn_process_rss_bytes=>1000000000,djinn_process_anon_rss_bytes=>900000000,djinn_jemalloc_allocated_bytes=>700000000,djinn_jemalloc_resident_bytes=>800000000,djinn_jemalloc_retained_bytes=>100000000,djinn_canonical_graph_slot_present=>$installed?1:0,djinn_canonical_graph_slot_approx_serialized_bytes=>$installed?$g->{requested_blob_bytes}:0,djinn_canonical_graph_slot_node_count=>$installed?$g->{requested_nodes}:0,djinn_canonical_graph_slot_edge_count=>$installed?$g->{requested_edges}:0); join('',map {"$_ $m{$_}\n"} @METRICS) }
sub metrics_from_text { my($text)=@_; my %m; for(split /\n/,$text){next if /^\s*(#|$)/; if(/^([^\s{]+)\s+([^\s]+)$/){$m{$1}=number($2,"metric $1")}} for(@METRICS){fail("metrics missing required signals: $_") unless exists $m{$_}} \%m }
sub metrics { my($installed)=@_; return metrics_from_text(fake_metrics_text($installed)) if $o{fake}; my $r=HTTP::Tiny->new(timeout=>20)->get($o{'metrics-url'}); fail('metrics endpoint unavailable') unless $r->{success}; metrics_from_text($r->{content}) }
sub galaxy_from_response { my($status,$headers,$latency)=@_; fail('galaxy endpoint unavailable') unless defined $status && $status=~/^\d+$/; (0+$status,$headers->{etag},$latency) }
sub galaxy { my($etag)=@_; my $start=time; return galaxy_from_response($etag?304:200,{etag=>'"fake-etag"'},(time-$start)*1000) if $o{fake}; my %h=(authorization=>'Bearer '.$ENV{$o{token_env}}); $h{'if-none-match'}=$etag if defined $etag; my $r=HTTP::Tiny->new(timeout=>120)->get($o{'galaxy-url'},{headers=>\%h}); galaxy_from_response($r->{status},$r->{headers},(time-$start)*1000) }
sub fixture_identity { my($v)=@_; for my $part(qw(seed checksums graph board_health galaxy_artifact)){fail("fixture inspection omitted $part") unless exists $v->{$part}} fail('fixture seed mismatch') unless $v->{seed} eq $profile->{seed}; for my $k(keys %{$profile->{checksums}}){fail("fixture checksum mismatch for $k") unless ($v->{checksums}{$k}//'') eq $profile->{checksums}{$k}} for my $pair(['graph','requested_nodes'],['graph','requested_edges'],['graph','requested_blob_bytes'],['board_health','requested_eligible_tasks'],['galaxy_artifact','requested_chunks'],['galaxy_artifact','requested_total_bytes']){my($p,$k)=@$pair; fail("fixture identity mismatch for $p.$k") unless defined $v->{$p}{$k} && $v->{$p}{$k}==$profile->{$p}{$k}} }
my $finished=0; $SIG{INT}=sub {die "__INTERRUPTED__\n"}; $SIG{TERM}=sub {die "__INTERRUPTED__\n"};
emit('run_metadata',run_id=>sprintf('%x-%x',time*1000000,$$),profile=>$o{profile},manifest_schema=>$manifest->{schema},manifest_version=>$manifest->{manifest_version},defaults=>{t0_seconds=>1800,t1_seconds=>900,burst_seconds=>7200,t2_seconds=>300,board_tick_seconds=>300,request_count=>100},overrides=>{map {$_=>$o{$_}} qw(t0_seconds t1_seconds burst_seconds t2_seconds board_tick_seconds request_count)},fake=>$o{fake});
eval { for my $k(qw(install-command board-command generation-command restart-command fixture-command)){fail("required $k was not supplied") unless $o{fake} || $o{$k}} my($limit,$current,$events)=cgroup(); fail("expected 4 GiB cgroup memory.max, got $limit") unless $limit==$GIB4; my $base=number(cmd_json($o{'restart-command'},'restart')->{restarts},'restart baseline'); my $fixture=cmd_json($o{'fixture-command'},'fixture'); fixture_identity($fixture); my $pre=metrics(0); fail('preflight requires no graph resident') unless $pre->{djinn_canonical_graph_slot_present}==0; my $bs=time; my $board=cmd_json($o{'board-command'},'board'); fail('board preflight did not report 40 pages') unless ($board->{pages}//0)==40; my($s200,$etag)=galaxy(undef); fail("galaxy preflight expected HTTP 200, got $s200") unless $s200==200 && $etag; my($s304)=galaxy($etag); fail("galaxy preflight expected HTTP 304, got $s304") unless $s304==304; emit('preflight',cgroup_limit=>$limit,cgroup_current=>$current,oom_baseline=>{oom=>$events->{oom},oom_kill=>$events->{oom_kill}},restart_baseline=>$base,fixture_observed=>$fixture,metrics=>$pre,board_duration_ms=>(time-$bs)*1000,galaxy_statuses=>[$s200,$s304]);
my $installed=0; my @samples; my $generation=sub {my($label)=@_; my $v=cmd_json($o{'generation-command'},'generation'); my $g=$v->{generation}//$v->{generation_id}; fail('generation command did not provide generation') unless defined $g && $g ne ''; emit('generation',label=>$label,generation=>$g); $g}; my $sample=sub {my($label,$resident,$g)=@_; my($max,$now,$ev)=cgroup(); my $m=metrics($installed); fail("$label graph-slot presence changed") unless $m->{djinn_canonical_graph_slot_present}==($resident?1:0); if($resident){my $x=$profile->{graph}; for my $p([djinn_canonical_graph_slot_node_count=>'requested_nodes'],[djinn_canonical_graph_slot_edge_count=>'requested_edges']){fail("$label fixture identity mismatch") unless $m->{$p->[0]}==$x->{$p->[1]}} my($lo,$hi)=@{$x->{required_blob_range_bytes}//[$x->{requested_blob_bytes},$x->{requested_blob_bytes}]}; fail("$label graph blob bytes outside manifest range") unless $m->{djinn_canonical_graph_slot_approx_serialized_bytes}>=$lo && $m->{djinn_canonical_graph_slot_approx_serialized_bytes}<=$hi} push @samples,$m; emit('sample',label=>$label,cgroup=>{memory_max=>$max,memory_current=>$now,events=>$ev},metrics=>$m,generation=>$g); $m}; my $wait=sub {my($phase,$seconds)=@_; emit('phase_wait',phase=>$phase,seconds=>$seconds); sleep($seconds) if $seconds};
$sample->('t0_before_idle',0); $wait->('t0_idle',$o{t0_seconds}); $sample->('T0',0); my $install=cmd_json($o{'install-command'},'install'); my $warm_peak=number($install->{warm_peak_bytes},'install warm_peak_bytes'); my $install_peak=number($install->{server_peak_bytes},'install server_peak_bytes'); emit('peak',phase=>'graph_install',warm_peak_bytes=>$warm_peak,server_peak_bytes=>$install_peak); $installed=1; my $g=$generation->('after_install'); $sample->('graph_install_peak',1,$g); $wait->('t1_quiescence',$o{t1_seconds}); $sample->('T1',1,$g); fail('graph generation replaced before burst') unless $generation->('t1') eq $g;
my $end=time+$o{burst_seconds}; my $next=time; my $burst_etag; my @route_rss; for my $i(0..$o{request_count}-1){if(time >= $next){my $s=time; my $b=cmd_json($o{'board-command'},'board'); fail('board pass did not report 40 pages') unless ($b->{pages}//0)==40; emit('board_pass',pages=>40,duration_ms=>(time-$s)*1000); $next += $o{board_tick_seconds} || 9e99} my $expected=$i%2?304:200; my $rss_before=metrics($installed)->{djinn_process_rss_bytes}; my($status,$new,$latency)=galaxy($expected==304?$burst_etag:undef); my $rss_after=metrics($installed)->{djinn_process_rss_bytes}; emit('galaxy_request',ordinal=>$i+1,expected_status=>$expected,status=>$status,etag=>$new,latency_ms=>$latency,rss_before_bytes=>$rss_before,rss_after_bytes=>$rss_after); push @route_rss,$rss_before,$rss_after; fail("galaxy request ".($i+1)." expected alternating HTTP $expected, got $status") unless $status==$expected; fail('200 galaxy response omitted ETag') if $expected==200 && !$new; $burst_etag=$new if $expected==200} while(time<$end){if(time >= $next){my $s=time; my $b=cmd_json($o{'board-command'},'board'); fail('board pass did not report 40 pages') unless ($b->{pages}//0)==40; emit('board_pass',pages=>40,duration_ms=>(time-$s)*1000); $next += $o{board_tick_seconds} || 9e99}else{sleep(.1)}} $sample->('burst_end',1,$g); fail('graph generation replaced during burst') unless $generation->('after_burst') eq $g; $wait->('t2_delay',$o{t2_seconds}); $sample->('T2',1,$g); fail('graph generation replaced before T2') unless $generation->('t2') eq $g; my(undef,undef,$end_events)=cgroup(); my $end_restart=number(cmd_json($o{'restart-command'},'restart')->{restarts},'restart counter'); my %oom=(oom=>$end_events->{oom}-$events->{oom},oom_kill=>$end_events->{oom_kill}-$events->{oom_kill}); emit('oom_delta',baseline=>{oom=>$events->{oom},oom_kill=>$events->{oom_kill}},current=>{oom=>$end_events->{oom},oom_kill=>$end_events->{oom_kill}},delta=>\%oom); emit('restart_delta',baseline=>$base,current=>$end_restart,delta=>$end_restart-$base); fail('OOM counter changed') if $oom{oom}>0 || $oom{oom_kill}>0; fail('restart counter changed') unless $end_restart==$base; my $server_peak=$install_peak; for(@samples,@route_rss){my $rss=ref $_ ? $_->{djinn_process_rss_bytes} : $_; $server_peak=$rss if $rss>$server_peak} emit('peak',phase=>'run',server_peak_bytes=>$server_peak,warm_peak_bytes=>$warm_peak); $finished=1;
}; my $err=$@; if($finished){emit('run_finalized',success=>JSON::PP::true); close $raw; move($partial,$o{output}) or die "finalize: $!\n"; exit 0} emit($err=~/__INTERRUPTED__/ ? 'interrupted':'failure',message=>($err||'unknown failure')); emit('run_finalized',success=>JSON::PP::false); close $raw; print STDERR $err; exit($err=~/__INTERRUPTED__/ ? 130:1);
