#!/usr/bin/env perl
# Production-image memory-sustainability workload driver.  It only orchestrates
# landed metrics, board scanner, galaxy REST, and graph-retention entry points.
use strict; use warnings;
use Getopt::Long qw(GetOptions); use JSON::PP; use HTTP::Tiny; use Time::HiRes qw(time sleep);
use File::Path qw(make_path); use File::Basename qw(dirname); use File::Copy qw(move);
my $SCHEMA='memory-sustainability-raw/v1'; my $GIB4=4*1024*1024*1024;
my @METRICS=qw(djinn_process_rss_bytes djinn_process_anon_rss_bytes djinn_jemalloc_allocated_bytes djinn_jemalloc_resident_bytes djinn_jemalloc_retained_bytes djinn_canonical_graph_slot_present djinn_canonical_graph_slot_approx_serialized_bytes djinn_canonical_graph_slot_node_count djinn_canonical_graph_slot_edge_count);
my $here=__FILE__; $here =~ s{/[^/]+$}{};
my %o=(manifest=>"$here/../fixtures/manifest.json",profile=>'production',t0_seconds=>1800,t1_seconds=>900,burst_seconds=>7200,t2_seconds=>300,board_tick_seconds=>300,request_count=>100,cgroup_root=>'/sys/fs/cgroup',token_env=>'DJINN_GALAXY_TOKEN');
GetOptions(\%o,'manifest=s','profile=s','output=s','metrics-url=s','galaxy-url=s','token-env=s','cgroup-root=s','install-command=s','board-command=s','generation-command=s','restart-command=s','t0-seconds=f','t1-seconds=f','burst-seconds=f','t2-seconds=f','board-tick-seconds=f','request-count=i','fake!') or die "invalid options\n";
for my $key (qw(t0 t1 burst t2 board_tick request)) { my $dash=$key; $dash =~ s/_/-/g; my $source=$dash . ($key eq 'request' ? '-count' : '-seconds'); my $target=$key . ($key eq 'request' ? '_count' : '_seconds'); $o{$target}=$o{$source} if exists $o{$source}; }
$o{'metrics-url'} //= $ENV{DJINN_METRICS_URL}; $o{'galaxy-url'} //= $ENV{DJINN_GALAXY_URL};
$o{'install-command'} //= $ENV{DJINN_GRAPH_INSTALL_COMMAND}; $o{'board-command'} //= $ENV{DJINN_BOARD_SCAN_COMMAND}; $o{'generation-command'} //= $ENV{DJINN_GRAPH_GENERATION_COMMAND}; $o{'restart-command'} //= $ENV{DJINN_RESTART_COUNTER_COMMAND};
die "--output is required\n" unless $o{output}; die "unknown profile\n" unless $o{profile}=~/^(production|smoke)$/;
die "durations must be nonnegative and request count positive\n" if grep {$o{$_}<0} qw(t0_seconds t1_seconds burst_seconds t2_seconds board_tick_seconds) or $o{request_count}<1;
die "metrics URL, galaxy URL, and nonempty token environment variable are required\n" unless $o{fake} || ($o{'metrics-url'} && $o{'galaxy-url'} && $ENV{$o{token_env}});
open my $mf,'<:raw',$o{manifest} or die "manifest: $!\n"; local $/; my $manifest=decode_json(<$mf>); close $mf;
die "invalid fixture manifest\n" unless $manifest->{schema} eq 'memory-sustainability-fixtures/v1' && $manifest->{profiles}{$o{profile}}; my $profile=$manifest->{profiles}{$o{profile}};
make_path(dirname($o{output})); my $partial="$o{output}.partial"; sysopen(my $raw,$partial,65|128) or die "refusing to overwrite evidence $partial: $!\n"; my $json=JSON::PP->new->canonical(1);
sub emit { my($kind,%x)=@_; print $raw $json->encode({schema=>$SCHEMA,kind=>$kind,timestamp=>scalar(gmtime()).'Z',%x})."\n"; $raw->flush; }
sub fail { die "memory workload failed: $_[0]\n" }
sub cmd_json { my($cmd,$what)=@_; return {pages=>40} if $o{fake} && $what eq 'board'; return {generation=>'fake-generation-v1',restarts=>0} if $o{fake}; fail("required $what command was not supplied") unless $cmd; my $out=`$cmd 2>&1`; fail("$what command failed") if $?; $out =~ s/^\s+|\s+$//g; return {generation=>$out} if $what eq 'generation' && $out ne '' && $out !~ /^\{/; return {restarts=>0+$out} if $what eq 'restart' && $out =~ /^\d+$/; my $v=eval {decode_json($out)}; fail("$what command must emit JSON") unless $v && ref $v eq 'HASH'; return $v; }
sub cgroup { return($GIB4,1000000000,{oom=>0,oom_kill=>0}) if $o{fake}; my $r=$o{cgroup_root}; open my $a,'<',"$r/memory.max" or fail("unreadable cgroup v2 signals"); my $limit=<$a>; close $a; chomp $limit; fail('cgroup memory.max is not numeric') unless $limit=~/^\d+$/; open my $b,'<',"$r/memory.current" or fail('unreadable cgroup v2 signals'); my $current=<$b>; close $b; chomp $current; open my $c,'<',"$r/memory.events" or fail('unreadable cgroup v2 signals'); my %e; while(<$c>){my($k,$v)=split; $e{$k}=0+$v} close $c; return(0+$limit,0+$current,\%e); }
sub fake_metrics { my($installed)=@_; my $g=$profile->{graph}; return {djinn_process_rss_bytes=>1000000000,djinn_process_anon_rss_bytes=>900000000,djinn_jemalloc_allocated_bytes=>700000000,djinn_jemalloc_resident_bytes=>800000000,djinn_jemalloc_retained_bytes=>100000000,djinn_canonical_graph_slot_present=>$installed?1:0,djinn_canonical_graph_slot_approx_serialized_bytes=>$installed?$g->{requested_blob_bytes}:0,djinn_canonical_graph_slot_node_count=>$installed?$g->{requested_nodes}:0,djinn_canonical_graph_slot_edge_count=>$installed?$g->{requested_edges}:0}; }
sub metrics { my($installed)=@_; return fake_metrics($installed) if $o{fake}; my $r=HTTP::Tiny->new(timeout=>20)->get($o{'metrics-url'}); fail('metrics endpoint unavailable') unless $r->{success}; my %m; for(split /\n/,$r->{content}) {next if /^\s*(#|$)/; if(/^([^\s{]+)\s+([^\s]+)$/){fail("malformed metric $1") unless $2=~/^-?(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?$/i; $m{$1}=0+$2}} for(@METRICS){fail("metrics missing required signals: $_") unless exists $m{$_}} return \%m; }
sub galaxy { my($i,$etag)=@_; my $start=time; return($i%2?304:200,'"fake-etag"',(time-$start)*1000) if $o{fake}; my %h=(authorization=>'Bearer '.$ENV{$o{token_env}}); $h{'if-none-match'}=$etag if $etag; my $r=HTTP::Tiny->new(timeout=>120)->get($o{'galaxy-url'},{headers=>\%h}); fail('galaxy endpoint unavailable') unless $r->{status}; return($r->{status},$r->{headers}{etag},(time-$start)*1000); }
my $finished=0; $SIG{INT}=sub { die "__INTERRUPTED__\n" }; $SIG{TERM}=sub { die "__INTERRUPTED__\n" };
emit('run_metadata',run_id=>sprintf('%x-%x',time*1000000,$$),profile=>$o{profile},manifest_schema=>$manifest->{schema},manifest_version=>$manifest->{manifest_version},defaults=>{t0_seconds=>1800,t1_seconds=>900,burst_seconds=>7200,t2_seconds=>300,board_tick_seconds=>300,request_count=>100},overrides=>{map {$_=>$o{$_}} qw(t0_seconds t1_seconds burst_seconds t2_seconds board_tick_seconds request_count)},fake=>$o{fake});
eval {
 for my $k (qw(install-command board-command generation-command restart-command)){fail("required $k was not supplied") unless $o{fake} || $o{$k}} my($limit)=cgroup(); fail("expected 4 GiB cgroup memory.max, got $limit") unless $limit==$GIB4; my $base=cmd_json($o{'restart-command'},'restart')->{restarts}; fail('restart command did not provide integer restarts') unless defined $base && $base=~/^\d+$/; emit('preflight',cgroup_limit=>$limit,fixture=>$profile,restart_baseline=>0+$base);
 my $installed=0; my $sample=sub {my($label)=@_; my($max,$current,$events)=cgroup(); my $m=metrics($installed); emit('sample',label=>$label,cgroup=>{memory_max=>$max,memory_current=>$current,events=>$events},metrics=>$m); return $m}; my $wait=sub {my($phase,$seconds)=@_; emit('phase_wait',phase=>$phase,seconds=>$seconds); sleep($seconds) if $seconds}; my $generation=sub {my($label)=@_; my $v=cmd_json($o{'generation-command'},'generation'); my $g=$v->{generation}//$v->{generation_id}; fail('generation command did not provide generation') unless defined $g && $g ne ''; emit('generation',label=>$label,generation=>$g); return $g};
 my $t0=$sample->('t0_before_idle'); fail('T0 requires no graph resident') unless $t0->{djinn_canonical_graph_slot_present}==0; $wait->('t0_idle',$o{t0_seconds}); $sample->('T0'); cmd_json($o{'install-command'},'install'); $installed=1; my $warm=$sample->('graph_install_peak'); my $g=$generation->('after_install'); my $graph=$profile->{graph}; for my $x ([djinn_canonical_graph_slot_node_count=>$graph->{requested_nodes}],[djinn_canonical_graph_slot_edge_count=>$graph->{requested_edges}]){fail("fixture identity mismatch for $x->[0]") unless $warm->{$x->[0]}==$x->[1]} my($lo,$hi)=@{$graph->{required_blob_range_bytes}//[$graph->{requested_blob_bytes},$graph->{requested_blob_bytes}]}; fail('fixture graph blob bytes outside manifest range') unless $warm->{djinn_canonical_graph_slot_approx_serialized_bytes}>=$lo && $warm->{djinn_canonical_graph_slot_approx_serialized_bytes}<=$hi;
 $wait->('t1_quiescence',$o{t1_seconds}); $sample->('T1'); fail('graph generation replaced before burst') unless $generation->('t1') eq $g; my $end=time+$o{burst_seconds}; my $next=time; my $etag; for my $i (0..$o{request_count}-1){if(time >= $next){my $s=time; my $b=cmd_json($o{'board-command'},'board'); fail('board pass did not report 40 pages') unless $b->{pages} && $b->{pages}==40; emit('board_pass',pages=>40,duration_ms=>(time-$s)*1000); $next += $o{board_tick_seconds} || 9e99} my $expected=$i%2?304:200; my($status,$new_etag,$latency)=galaxy($i,$expected==304?$etag:undef); emit('galaxy_request',ordinal=>$i+1,expected_status=>$expected,status=>$status,etag=>$new_etag,latency_ms=>$latency); fail("galaxy request ".($i+1)." expected alternating HTTP $expected, got $status") unless $status==$expected; fail('200 galaxy response omitted ETag') if $expected==200 && !$new_etag; $etag=$new_etag if $expected==200; }
 while(time<$end){if(time >= $next){my $s=time; my $b=cmd_json($o{'board-command'},'board'); fail('board pass did not report 40 pages') unless $b->{pages} && $b->{pages}==40; emit('board_pass',pages=>40,duration_ms=>(time-$s)*1000); $next += $o{board_tick_seconds} || 9e99}else{sleep(.1)}} $sample->('burst_end'); fail('graph generation replaced during burst') unless $generation->('after_burst') eq $g; $wait->('t2_delay',$o{t2_seconds}); $sample->('T2'); fail('graph generation replaced before T2') unless $generation->('t2') eq $g; my $end_restart=cmd_json($o{'restart-command'},'restart')->{restarts}; fail('restart counter changed') unless defined $end_restart && $end_restart==$base; emit('restart_delta',baseline=>0+$base,current=>0+$end_restart,delta=>$end_restart-$base); $finished=1;
}; my $err=$@; if($finished){emit('run_finalized',success=>JSON::PP::true); close $raw; move($partial,$o{output}) or die "finalize: $!\n"; exit 0} emit($err=~/__INTERRUPTED__/ ? 'interrupted':'failure',message=>($err||'unknown failure')); emit('run_finalized',success=>JSON::PP::false); close $raw; print STDERR $err; exit($err=~/__INTERRUPTED__/ ? 130:1);
