use strict; use warnings; use Test::More;
use File::Temp qw(tempdir); use File::Spec; use JSON::PP;
my $root = File::Spec->rel2abs(File::Spec->catdir(File::Spec->curdir));
$root =~ s{/server/docs/operational/memory-sustainability/driver/tests\z}{};
my $driver = "$root/server/docs/operational/memory-sustainability/driver/memory_workload.pl";
my $dir=tempdir(CLEANUP=>1); my $out="$dir/smoke.jsonl";
my @cmd=('perl',$driver,'--fake','--profile','smoke','--output',$out,'--t0-seconds','0','--t1-seconds','0','--burst-seconds','0','--t2-seconds','0','--request-count','6');
is(system(@cmd),0,'fixture-backed fake state machine and production-format parsers succeed');
open my $fh,'<',$out or die $!; my @r=map {decode_json($_)} <$fh>; close $fh;
is($r[0]{defaults}{t0_seconds},1800,'production T0 default remains encoded');
is($r[0]{defaults}{burst_seconds},7200,'production burst default remains encoded');
my @requests=grep {$_->{kind} eq 'galaxy_request'} @r;
is_deeply([map {$_->{status}} @requests],[200,304,200,304,200,304],'requests alternate 200/304');
ok(scalar(grep {$_->{kind} eq 'preflight' && $_->{fixture_observed}{seed} eq 'ste6-smoke-v1'} @r),'preflight observes fixture identity before install');
ok(scalar(grep {$_->{kind} eq 'oom_delta'} @r),'OOM baseline and delta are preserved');
ok(scalar(grep {$_->{kind} eq 'peak' && $_->{warm_peak_bytes}} @r),'warm and server peaks are recorded');
ok(!-e "$out.partial",'successful evidence finalized atomically');
my $bad="$dir/malformed.jsonl";
{ local $ENV{DJINN_FAKE_MALFORMED}='events';
  isnt(system('perl',$driver,'--fake','--profile','smoke','--output',$bad,'--t0-seconds','0','--t1-seconds','0','--burst-seconds','0','--t2-seconds','0','--request-count','1'),0,'malformed cgroup events fail preflight');
}
ok(-e "$bad.partial",'malformed preflight preserves partial raw evidence');
open $fh,'<',"$bad.partial" or die $!; my @bad=map {decode_json($_)} <$fh>; close $fh;
ok($bad[-1]{kind} eq 'run_finalized' && !$bad[-1]{success},'failed partial evidence is finalized as unsuccessful');
my $interrupted="$dir/interrupted.jsonl";
my $pid=fork(); die "fork: $!" unless defined $pid;
if(!$pid){ exec 'perl',$driver,'--fake','--profile','smoke','--output',$interrupted,'--t0-seconds','5','--t1-seconds','0','--burst-seconds','0','--t2-seconds','0','--request-count','1'; die "exec: $!"; }
sleep 1; kill 'TERM',$pid; waitpid($pid,0);
is($? >> 8,130,'SIGTERM returns interrupted status');
ok(-e "$interrupted.partial",'interruption preserves partial evidence');
open $fh,'<',"$interrupted.partial" or die $!; my @int=map {decode_json($_)} <$fh>; close $fh;
is($int[-2]{kind},'interrupted','interruption record precedes finalization');
my $invalid="$dir/invalid.jsonl";
isnt(system('perl',$driver,'--fake','--profile','smoke','--output',$invalid,'--t0-seconds','0','--t1-seconds','0','--burst-seconds','0','--t2-seconds','0','--request-count','0'),0,'invalid override fails before workload');
done_testing;
