# syntax=docker/dockerfile:1.7
# Generated by djinn-image-builder — DO NOT EDIT.

FROM debian:bookworm-slim
COPY scripts/ /tmp/djinn-scripts/
RUN chmod -R 0755 /tmp/djinn-scripts
RUN /tmp/djinn-scripts/base-debian.sh
RUN APT_PACKAGES="postgresql-client" /tmp/djinn-scripts/install-system.sh
COPY --from=djinn/agent-worker:sha256-golden /opt/djinn/bin/djinn-agent-worker /opt/djinn/bin/djinn-agent-worker
RUN /tmp/djinn-scripts/install-agent-worker.sh
RUN TOOLCHAINS="stable 1.85.0" DEFAULT_TOOLCHAIN="stable" COMPONENTS="rust-analyzer" /tmp/djinn-scripts/install-rust.sh
RUN NODE_VERSIONS="22 20" DEFAULT_NODE="22" PACKAGE_MANAGERS="pnpm" /tmp/djinn-scripts/install-node.sh
RUN PYTHON_VERSIONS="3.12" DEFAULT_PYTHON="3.12" SCIP_INDEXER="scip-python" /tmp/djinn-scripts/install-python.sh
ENV RUST_LOG=info
RUN rm -rf /tmp/djinn-scripts
