# syntax=docker/dockerfile:1.7
# Generated by djinn-image-builder — DO NOT EDIT.

FROM debian:bookworm-slim
COPY scripts/ /tmp/djinn-scripts/
RUN chmod -R 0755 /tmp/djinn-scripts
RUN /tmp/djinn-scripts/base-debian.sh
COPY --from=djinn/agent-worker:sha256-golden /opt/djinn/bin/djinn-agent-worker /opt/djinn/bin/djinn-agent-worker
RUN /tmp/djinn-scripts/install-agent-worker.sh
RUN TOOLCHAINS="1.84.0" DEFAULT_TOOLCHAIN="1.84.0" COMPONENTS="clippy rust-analyzer" /tmp/djinn-scripts/install-rust.sh
RUN rm -rf /tmp/djinn-scripts
