# syntax=docker/dockerfile:1.7
# Generated by djinn-image-builder — DO NOT EDIT.

FROM debian:bookworm-slim
COPY scripts/ /tmp/djinn-scripts/
RUN chmod -R 0755 /tmp/djinn-scripts
RUN /tmp/djinn-scripts/base-debian.sh
ENV PATH=/opt/djinn/bin:/usr/local/cargo/bin:/opt/node/bin:/usr/local/go/bin:/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV RUSTUP_HOME=/usr/local/rustup CARGO_HOME=/usr/local/cargo
ENV GOPATH=/go GOROOT=/usr/local/go
COPY --from=djinn/agent-worker:sha256-golden /usr/local/bin/djinn-agent-worker /opt/djinn/bin/djinn-agent-worker
RUN /tmp/djinn-scripts/install-agent-worker.sh
RUN TOOLCHAINS="1.84.0" DEFAULT_TOOLCHAIN="1.84.0" COMPONENTS="rust-analyzer" /tmp/djinn-scripts/install-rust.sh
RUN rm -rf /tmp/djinn-scripts
