# syntax=docker/dockerfile:1.7
# Generated by djinn-image-builder — DO NOT EDIT.

FROM debian:trixie-slim
COPY scripts/ /tmp/djinn-scripts/
RUN chmod -R 0755 /tmp/djinn-scripts
RUN /tmp/djinn-scripts/base-debian.sh
ENV PATH=/opt/djinn/bin:/usr/local/cargo/bin:/opt/node/bin:/usr/local/go/bin:/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/cache/go/bin
ENV HOME=/home/djinn
ENV RUSTUP_HOME=/usr/local/rustup CARGO_HOME=/usr/local/cargo
ENV GOPATH=/go GOROOT=/usr/local/go
ENV GOMODCACHE=/cache/go/mod GOCACHE=/cache/go/build GOBIN=/cache/go/bin
ENV PNPM_HOME=/cache/pnpm npm_config_cache=/cache/npm YARN_CACHE_FOLDER=/cache/yarn
ENV PIP_CACHE_DIR=/cache/pip UV_CACHE_DIR=/cache/uv
COPY --from=djinn/agent-worker:sha256-golden /usr/local/bin/djinn-agent-worker /opt/djinn/bin/djinn-agent-worker
COPY --from=djinn/agent-worker:sha256-golden /usr/local/bin/djinn-cgroup-launcher /opt/djinn/bin/djinn-cgroup-launcher
RUN /tmp/djinn-scripts/install-agent-worker.sh
RUN TOOLCHAINS="1.84.0" DEFAULT_TOOLCHAIN="1.84.0" COMPONENTS="rust-analyzer clippy rustfmt" /tmp/djinn-scripts/install-rust.sh
RUN rm -rf /tmp/djinn-scripts
RUN [ -d /usr/local/rustup ] && chmod -R a+rwX /usr/local/rustup || true; [ -d /usr/local/cargo ] && chmod -R a+rwX /usr/local/cargo || true
