{{- if .Values.imagePipeline.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "djinn.fullname" . }}-buildkitd
  namespace: {{ include "djinn.namespace" . }}
  labels:
    {{- include "djinn.labels" . | nindent 4 }}
    app.kubernetes.io/component: buildkitd
spec:
  type: ClusterIP
  selector:
    {{- include "djinn.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: buildkitd
  ports:
    - name: grpc
      port: {{ .Values.imagePipeline.buildkitd.port }}
      targetPort: grpc
      protocol: TCP
{{- end -}}
