{{- if and .Values.langfuse.enabled (not .Values.langfuse.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "djinn.secretName.langfuse" . }}
  namespace: {{ include "djinn.namespace" . }}
  labels:
    {{- include "djinn.server.labels" . | nindent 4 }}
type: Opaque
stringData:
  DJINN_LANGFUSE_PUBLIC_KEY: {{ .Values.langfuse.publicKey | quote }}
  DJINN_LANGFUSE_SECRET_KEY: {{ .Values.langfuse.secretKey | quote }}
{{- end -}}
