apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "djinn.serviceAccountName.controller" . }}
  namespace: {{ include "djinn.namespace" . }}
  labels:
    {{- include "djinn.server.labels" . | nindent 4 }}
